-- ===========================================================================
-- PC Builders Canada - catalogue additions
-- ===========================================================================
-- GENERATED FILE - do not edit by hand.
-- Source: src/lib/catalog/sample-catalog.ts
-- Regenerate with: SEED_ONLY_SINCE=<YYYY-MM-DD> npm run db:seed:generate
--
-- ADDITIVE ONLY. This ends in `on conflict (id) do nothing`, so running it
-- against a database that already holds one of these ids changes NOTHING about
-- that row: its price, stock, status and uploaded product photo are left as
-- they are.
--
-- Use this rather than seed.sql to add parts to a catalogue that is already in
-- service. seed.sql overwrites image_url with null for every row it knows
-- about, which erases uploaded photography.
--
-- Rows: 36
-- ===========================================================================

insert into components (
  id,
  sku,
  slug,
  category,
  brand,
  model,
  description,
  price_cents,
  cost_cents,
  stock_quantity,
  low_stock_threshold,
  image_url,
  status,
  data_confidence,
  condition,
  condition_notes,
  socket,
  supported_sockets,
  chipset,
  memory_slots,
  max_memory_gb,
  m2_slots,
  sata_ports,
  form_factor,
  supported_form_factors,
  memory_type,
  memory_capacity_gb,
  memory_modules,
  memory_speed_mts,
  tdp_watts,
  recommended_psu_watts,
  psu_wattage,
  psu_efficiency,
  psu_form_factor,
  gpu_length_mm,
  max_gpu_length_mm,
  cooler_height_mm,
  max_cooler_height_mm,
  radiator_support_mm,
  radiator_size_mm,
  cooler_type,
  cooling_capacity_watts,
  storage_interface,
  storage_capacity_gb,
  pcie_version,
  specs
) values
  ('cpu-amd-ryzen-5-9600x', 'CPU-AMD-R59600X', 'cpu-amd-ryzen-5-9600x', 'cpu', 'AMD', 'Ryzen 5 9600X', 'Six-core Zen 5 processor and the sensible floor for a new AM5 build. 65 W, so a modest cooler is enough.', 39900, null, 5, 3, null, 'published', 'verified', 'new', null, 'AM5', null, null, null, null, null, null, null, null, 'ddr5', null, null, null, 65, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"cores":6,"threads":12,"integrated_graphics":true,"source":"Canada Computers","sale_price_observed":"$279.98 on 2026-10-06","price_checked":"2026-10-06"}'::jsonb),
  ('cpu-amd-ryzen-7-9700x', 'CPU-AMD-R79700X', 'cpu-amd-ryzen-7-9700x', 'cpu', 'AMD', 'Ryzen 7 9700X', 'Eight-core Zen 5 processor at 65 W. The all-round choice when the build is as much work as it is games.', 51900, null, 5, 3, null, 'published', 'verified', 'new', null, 'AM5', null, null, null, null, null, null, null, null, 'ddr5', null, null, null, 65, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"cores":8,"threads":16,"integrated_graphics":true,"source":"Canada Computers","price_checked":"2026-10-06"}'::jsonb),
  ('cpu-amd-ryzen-9-9900x', 'CPU-AMD-R99900X', 'cpu-amd-ryzen-9-9900x', 'cpu', 'AMD', 'Ryzen 9 9900X', 'Twelve cores for rendering, compiling and anything that scales past eight. 120 W, so plan the cooler around it.', 64900, null, 5, 3, null, 'published', 'verified', 'new', null, 'AM5', null, null, null, null, null, null, null, null, 'ddr5', null, null, null, 120, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"cores":12,"threads":24,"integrated_graphics":true,"source":"Canada Computers","sale_price_observed":"$519.99 on 2026-10-06","price_checked":"2026-10-06"}'::jsonb),
  ('cpu-amd-ryzen-9-9900x3d', 'CPU-AMD-R99900X3D', 'cpu-amd-ryzen-9-9900x3d', 'cpu', 'AMD', 'Ryzen 9 9900X3D', 'Twelve cores with 3D V-Cache: gaming performance close to the 9800X3D without giving up the core count for work.', 84900, null, 5, 3, null, 'published', 'verified', 'new', null, 'AM5', null, null, null, null, null, null, null, null, 'ddr5', null, null, null, 120, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"cores":12,"threads":24,"cache":"140 MB total","integrated_graphics":true,"source":"Canada Computers","sale_price_observed":"$799.99 on 2026-10-06","price_checked":"2026-10-06"}'::jsonb),
  ('cpu-amd-ryzen-9-9950x3d', 'CPU-AMD-R99950X3D', 'cpu-amd-ryzen-9-9950x3d', 'cpu', 'AMD', 'Ryzen 9 9950X3D', 'Sixteen cores with 3D V-Cache. The one to pick when the same machine has to game and earn its keep. 170 W.', 99900, null, 5, 3, null, 'published', 'verified', 'new', null, 'AM5', null, null, null, null, null, null, null, null, 'ddr5', null, null, null, 170, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"cores":16,"threads":32,"cache":"144 MB total","integrated_graphics":true,"source":"Canada Computers","sale_price_observed":"$929.98 on 2026-10-06","price_checked":"2026-10-06"}'::jsonb),
  ('cpu-intel-core-ultra-7-265kf', 'CPU-INT-U7265KF', 'cpu-intel-core-ultra-7-265kf', 'cpu', 'Intel', 'Core Ultra 7 265KF', 'Twenty cores on LGA1851. The KF has no integrated graphics, which is a saving if a graphics card is going in anyway.', 41999, null, 5, 3, null, 'published', 'sample', 'new', null, 'LGA1851', null, null, null, null, null, null, null, null, 'ddr5', null, null, null, 125, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"cores":"20 (8P + 12E)","integrated_graphics":false,"chipset_support":"B860, H810, H870, Z890","source":"Canada Computers","sale_price_observed":"$339.99 on 2026-10-06","unverified":"Base power is the Intel figure for the Core Ultra 7 265K/KF; the retailer listing states the socket and core layout but not the wattage.","price_checked":"2026-10-06"}'::jsonb),
  ('cpu-amd-ryzen-7-5700x', 'CPU-AMD-R75700X', 'cpu-amd-ryzen-7-5700x', 'cpu', 'AMD', 'Ryzen 7 5700X', 'Eight-core AM4 processor at 65 W. The cheapest route to eight cores, and the sensible upgrade for an existing AM4 machine.', 38999, null, 5, 3, null, 'published', 'verified', 'new', null, 'AM4', null, null, null, null, null, null, null, null, 'ddr4', null, null, null, 65, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 4, '{"cores":8,"threads":16,"integrated_graphics":false,"source":"Canada Computers","sale_price_observed":"$289.99 on 2026-10-06","price_checked":"2026-10-06"}'::jsonb),
  ('cpu-intel-core-i5-14400', 'CPU-INT-I514400', 'cpu-intel-core-i5-14400', 'cpu', 'Intel', 'Core i5-14400', 'Ten-core LGA1700 processor at 65 W. The budget entry to a platform where boards and DDR4 memory are cheap.', 25900, null, 5, 3, null, 'published', 'sample', 'new', null, 'LGA1700', null, null, null, null, null, null, null, null, null, null, null, null, 65, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"cores":"10 (6P + 4E)","integrated_graphics":true,"memory_support":"DDR4 or DDR5, depending on the motherboard","source":"Canada Computers","unverified":"Base power is the Intel figure for the i5-14400; the retailer listing states the socket and core layout but not the wattage.","price_checked":"2026-10-06"}'::jsonb),
  ('cpu-intel-core-i5-14600k', 'CPU-INT-I514600K', 'cpu-intel-core-i5-14600k', 'cpu', 'Intel', 'Core i5-14600K', 'Fourteen cores, unlocked. The mid-range LGA1700 gaming choice.', 47999, null, 5, 3, null, 'published', 'sample', 'new', null, 'LGA1700', null, null, null, null, null, null, null, null, null, null, null, null, 125, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"cores":"14 (6P + 8E)","integrated_graphics":true,"memory_support":"DDR4 or DDR5, depending on the motherboard","source":"Canada Computers","sale_price_observed":"$349.99 on 2026-10-06","unverified":"Base power is the Intel figure; the retailer listing does not state wattage.","price_checked":"2026-10-06"}'::jsonb),
  ('cpu-intel-core-i7-14700k', 'CPU-INT-I714700K', 'cpu-intel-core-i7-14700k', 'cpu', 'Intel', 'Core i7-14700K', 'Twenty cores, unlocked. Strong at both games and heavily threaded work, and the reason LGA1700 is still worth building on.', 61999, null, 5, 3, null, 'published', 'sample', 'new', null, 'LGA1700', null, null, null, null, null, null, null, null, null, null, null, null, 125, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"cores":"20 (8P + 12E)","integrated_graphics":true,"memory_support":"DDR4 or DDR5, depending on the motherboard","source":"Canada Computers","sale_price_observed":"$539.99 on 2026-10-06","unverified":"Base power is the Intel figure; the retailer listing does not state wattage.","price_checked":"2026-10-06"}'::jsonb),
  ('cpu-intel-core-i9-14900k', 'CPU-INT-I914900K', 'cpu-intel-core-i9-14900k', 'cpu', 'Intel', 'Core i9-14900K', 'Twenty-four cores, unlocked. Plan the cooling around it rather than after it.', 74999, null, 5, 3, null, 'published', 'sample', 'new', null, 'LGA1700', null, null, null, null, null, null, null, null, null, null, null, null, 125, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"cores":"24 (8P + 16E)","integrated_graphics":true,"memory_support":"DDR4 or DDR5, depending on the motherboard","source":"Canada Computers","sale_price_observed":"$549.99 on 2026-10-06","unverified":"Base power is the Intel figure; the retailer listing does not state wattage.","price_checked":"2026-10-06"}'::jsonb),
  ('mb-asus-tuf-b650e-plus-wifi', 'MB-ASU-B650EPLUS', 'mb-asus-tuf-b650e-plus-wifi', 'motherboard', 'ASUS', 'TUF GAMING B650E-PLUS WIFI', 'AM5 board with four DIMM slots and three M.2 slots, which is the practical middle of the range: room to add storage later without paying for an X870E.', 27999, null, 5, 3, null, 'published', 'verified', 'new', null, 'AM5', null, 'B650', 4, 256, 3, 4, 'atx', null, 'ddr5', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"wifi":"Wi-Fi 6E","cpu_support":"Ryzen 9000, 8000 and 7000 series","source":"Canada Computers (price), ASUS techspec (specifications)","price_checked":"2026-10-06"}'::jsonb),
  ('mb-asus-prime-b550-plus-ac-hes', 'MB-ASU-B550PLUSAC', 'mb-asus-prime-b550-plus-ac-hes', 'motherboard', 'ASUS', 'PRIME B550-PLUS AC-HES', 'AM4 board with six SATA ports, which is more than most current boards offer and the reason this platform is still good for a storage-heavy build.', 15999, null, 5, 3, null, 'published', 'verified', 'new', null, 'AM4', null, 'B550', 4, 128, 2, 6, 'atx', null, 'ddr4', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 4, '{"wifi":"Wi-Fi 5 (AC)","cpu_support":"Ryzen 5000 and 3000 series","source":"PBC catalogue sheet (price, slots, max memory), ASUS techspec (chipset, form factor, M.2, SATA, PCIe)","price_checked":"2026-10-06"}'::jsonb),
  ('mb-asus-tuf-z790-plus-wifi-d4', 'MB-ASU-Z790PLUSD4', 'mb-asus-tuf-z790-plus-wifi-d4', 'motherboard', 'ASUS', 'TUF GAMING Z790-PLUS WIFI D4', 'LGA1700 board that takes DDR4, which is what makes this platform cheap to build on. Four M.2 slots is generous at the price.', 27999, null, 5, 3, null, 'published', 'verified', 'new', null, 'LGA1700', null, 'Z790', 4, 128, 4, 4, 'atx', null, 'ddr4', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"wifi":"Wi-Fi 6","cpu_support":"Intel 12th, 13th and 14th generation","source":"PBC catalogue sheet (price), ASUS techspec (specifications)","price_checked":"2026-10-06"}'::jsonb),
  ('cool-deepcool-ak400-digital-se', 'COOL-DC-AK400DSE', 'cool-deepcool-ak400-digital-se', 'cooler', 'DeepCool', 'AK400 DIGITAL SE', 'Single-tower air cooler with a temperature display on the cap. The budget end of the range, and enough for any 65 W processor here.', 3999, null, 5, 3, null, 'published', 'sample', 'new', null, null, array['AM5', 'AM4', 'LGA1851', 'LGA1700', 'LGA1200', 'LGA1151', 'LGA1150', 'LGA1155'], null, null, null, null, null, null, null, null, null, null, null, 3, null, null, null, null, null, null, 157, null, null, null, 'air', null, null, null, null, '{"fan":"120 mm FDB, 500-1850 RPM","heat_pipes":4,"display":"CPU temperature and load","dimensions_mm":"126 x 97 x 157","source":"Canada Computers (price), DeepCool product page (specifications)","unverified":"DeepCool publishes no TDP rating for this cooler, so none is recorded and the engine does not compare it against a processor. Height and socket support are the manufacturer figures.","price_checked":"2026-10-06"}'::jsonb),
  ('gpu-asus-prime-rtx-5070-oc', 'GPU-ASU-5070POC', 'gpu-asus-prime-rtx-5070-oc', 'gpu', 'ASUS', 'Prime GeForce RTX 5070 OC Edition 12GB', '1440p card with 12 GB of GDDR7. A 304 mm board, so check it against the case clearance before ordering.', 129999, null, 5, 3, null, 'published', 'sample', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, 250, null, null, null, null, 304, null, null, null, null, null, null, null, null, null, 5, '{"vram_gb":12,"memory":"GDDR7 192-bit, 28 Gbps","power_connectors":"1x 16-pin","source":"Canada Computers","unverified":"Board power is the NVIDIA reference figure for the RTX 5070, not an ASUS figure for this card. No recommended PSU wattage was stated by the retailer, so none is recorded.","price_checked":"2026-10-05"}'::jsonb),
  ('gpu-sapphire-pulse-rx-9060-xt-16gb', 'GPU-SAP-9060XT16', 'gpu-sapphire-pulse-rx-9060-xt-16gb', 'gpu', 'SAPPHIRE', 'PULSE Radeon RX 9060 XT Gaming OC 16GB', '1080p and 1440p card with 16 GB of memory, which ages better than raw speed in newer titles. 285 mm, so it fits more cases than the larger cards above it.', 84999, null, 5, 3, null, 'published', 'sample', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, 160, 650, null, null, null, 285, null, null, null, null, null, null, null, null, null, 5, '{"vram_gb":16,"memory":"GDDR6 128-bit","power_connectors":"1x 8-pin","source":"Canada Computers","unverified":"Board power is the AMD reference figure for the RX 9060 XT. The recommended 650 W is the retailer-stated figure for this card.","price_checked":"2026-10-05"}'::jsonb),
  ('gpu-gigabyte-rx-9070-xt-gaming-oc', 'GPU-GIG-9070XTG', 'gpu-gigabyte-rx-9070-xt-gaming-oc', 'gpu', 'Gigabyte', 'Radeon RX 9070 XT GAMING OC 16GB', '1440p and 4K card with 16 GB of memory. At 288 mm it is the shortest of the 9070 XT boards listed here, which matters in a compact case.', 149900, null, 5, 3, null, 'published', 'sample', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, 304, 850, null, null, null, 288, null, null, null, null, null, null, null, null, null, 5, '{"vram_gb":16,"memory":"GDDR6 256-bit","power_connectors":"2x 8-pin","source":"Canada Computers","sale_price_observed":"$1,049.00 on 2026-10-05","unverified":"Board power and the recommended 850 W are the AMD reference figures for the RX 9070 XT, not Gigabyte figures for this card.","price_checked":"2026-10-05"}'::jsonb),
  ('gpu-asus-prime-rx-9070-xt-oc', 'GPU-ASU-9070XTP', 'gpu-asus-prime-rx-9070-xt-oc', 'gpu', 'ASUS', 'Prime Radeon RX 9070 XT OC Edition 16GB', '1440p and 4K card with 16 GB of memory and a triple-fan cooler. 312 mm long.', 153999, null, 5, 3, null, 'published', 'sample', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, 304, 850, null, null, null, 312, null, null, null, null, null, null, null, null, null, 5, '{"vram_gb":16,"memory":"GDDR6 256-bit","power_connectors":"2x 8-pin","source":"Canada Computers","unverified":"Board power and the recommended 850 W are the AMD reference figures for the RX 9070 XT, not ASUS figures for this card.","price_checked":"2026-10-05"}'::jsonb),
  ('gpu-sapphire-pure-rx-9070-xt', 'GPU-SAP-9070XTPU', 'gpu-sapphire-pure-rx-9070-xt', 'gpu', 'SAPPHIRE', 'PURE Radeon RX 9070 XT 16GB', 'The white-shroud 9070 XT, for a build where the parts are meant to match. Same 16 GB and the same 320 mm length as the PULSE.', 144900, null, 5, 3, null, 'published', 'sample', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, 304, 850, null, null, null, 320, null, null, null, null, null, null, null, null, null, 5, '{"vram_gb":16,"memory":"GDDR6 256-bit","power_connectors":"2x 8-pin","colour":"White","source":"Canada Computers","unverified":"Board power and the recommended 850 W are the AMD reference figures for the RX 9070 XT, not SAPPHIRE figures for this card.","price_checked":"2026-10-05"}'::jsonb),
  ('ram-corsair-vengeance-lpx-32gb-ddr4-3200', 'RAM-COR-32G3200D4', 'ram-corsair-vengeance-lpx-32gb-ddr4-3200', 'ram', 'Corsair', 'VENGEANCE LPX 32GB (2x16GB) DDR4-3200 CL16', 'DDR4 for an AM4 or DDR4 LGA1700 build. Low-profile heatspreaders, so it clears a tall air cooler.', 43599, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, 'ddr4', 32, 2, 3200, 6, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"cas_latency":"CL16","form":"UDIMM","source":"Canada Computers","sale_price_observed":"$349.99 on 2026-10-06","price_checked":"2026-10-06"}'::jsonb),
  ('ram-corsair-vengeance-rgb-32gb-ddr5-6000', 'RAM-COR-32G6000', 'ram-corsair-vengeance-rgb-32gb-ddr5-6000', 'ram', 'Corsair', 'VENGEANCE RGB 32GB (2x16GB) DDR5-6000 CL30', 'The common 32 GB sweet spot for a gaming build, at the CL30 timing AM5 prefers.', 88699, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, 'ddr5', 32, 2, 6000, 8, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"cas_latency":"CL30","form":"UDIMM","source":"Canada Computers","price_checked":"2026-10-06"}'::jsonb),
  ('ram-corsair-vengeance-rgb-64gb-ddr5-6000', 'RAM-COR-64G6000', 'ram-corsair-vengeance-rgb-64gb-ddr5-6000', 'ram', 'Corsair', 'VENGEANCE RGB 64GB (2x32GB) DDR5-6000 CL30', 'Two sticks rather than four for 64 GB, which is the configuration AM5 runs at full speed more reliably.', 177999, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, 'ddr5', 64, 2, 6000, 10, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"cas_latency":"CL30","form":"UDIMM","source":"Canada Computers","price_checked":"2026-10-06"}'::jsonb),
  ('ram-gskill-trident-z5-neo-32gb-ddr5-6000', 'RAM-GSK-32G6000', 'ram-gskill-trident-z5-neo-32gb-ddr5-6000', 'ram', 'G.SKILL', 'Trident Z5 Neo RGB 32GB (2x16GB) DDR5-6000 CL30', 'EXPO-tuned 32 GB kit aimed at Ryzen. The Neo line is the AMD-profile version of the Trident Z5.', 108999, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, 'ddr5', 32, 2, 6000, 8, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"cas_latency":"CL30","form":"UDIMM","source":"Canada Computers","price_checked":"2026-10-06"}'::jsonb),
  ('ram-kingston-fury-beast-64gb-ddr5-6000', 'RAM-KIN-64G6000', 'ram-kingston-fury-beast-64gb-ddr5-6000', 'ram', 'Kingston', 'FURY Beast 64GB (2x32GB) DDR5-6000 CL30', '64 GB for rendering, virtual machines and large datasets.', 188999, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, 'ddr5', 64, 2, 6000, 10, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"cas_latency":"CL30","form":"UDIMM","source":"Canada Computers","price_checked":"2026-10-06"}'::jsonb),
  ('ssd-samsung-990-pro-1tb', 'SSD-SAM-990P1T', 'ssd-samsung-990-pro-1tb', 'storage', 'Samsung', '990 Pro 1TB NVMe', 'Gen4 drive with a DRAM cache. A safe boot drive where sustained write speed matters more than a benchmark number.', 43999, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, 7, null, null, null, null, null, null, null, null, null, null, null, null, 'nvme-m2', 1000, 4, '{"form_factor":"M.2 2280","dram_cache":true,"source":"Canada Computers","price_checked":"2026-10-06"}'::jsonb),
  ('ssd-samsung-9100-pro-1tb', 'SSD-SAM-9100P1T', 'ssd-samsung-9100-pro-1tb', 'storage', 'Samsung', '9100 PRO 1TB PCIe Gen5 NVMe', 'PCIe Gen5 drive. Worth it on a Gen5 M.2 slot and wasted on a Gen4 one, where it runs at Gen4 speed.', 46499, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, 7, null, null, null, null, null, null, null, null, null, null, null, null, 'nvme-m2', 1000, 5, '{"form_factor":"M.2 2280","source":"Canada Computers","sale_price_observed":"$249.99 on 2026-10-06","price_checked":"2026-10-06"}'::jsonb),
  ('ssd-samsung-9100-pro-2tb', 'SSD-SAM-9100P2T', 'ssd-samsung-9100-pro-2tb', 'storage', 'Samsung', '9100 PRO 2TB PCIe Gen5 NVMe', 'PCIe Gen5 drive at the capacity most single-drive builds actually want.', 92499, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, 7, null, null, null, null, null, null, null, null, null, null, null, null, 'nvme-m2', 2000, 5, '{"form_factor":"M.2 2280","source":"Canada Computers","sale_price_observed":"$489.99 on 2026-10-06","price_checked":"2026-10-06"}'::jsonb),
  ('ssd-wd-black-sn850x-4tb', 'SSD-WD-SN850X4T', 'ssd-wd-black-sn850x-4tb', 'storage', 'Western Digital', 'WD_BLACK SN850X 4TB NVMe', 'The 4 TB SN850X, for a single-drive machine with a large game library.', 151999, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, 7, null, null, null, null, null, null, null, null, null, null, null, null, 'nvme-m2', 4000, 4, '{"form_factor":"M.2 2280","dram_cache":true,"source":"Canada Computers","sale_price_observed":"$949.99 on 2026-10-06","price_checked":"2026-10-06"}'::jsonb),
  ('psu-fsp-vita-750w', 'PSU-FSP-VITA750', 'psu-fsp-vita-750w', 'psu', 'FSP', 'VITA 750W 80 PLUS Gold', '750 W Gold unit, enough for a single mid-range card with headroom to spare.', 13999, null, 5, 3, null, 'published', 'sample', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 750, '80 PLUS Gold', 'atx', null, null, null, null, null, null, null, null, null, null, null, '{"source":"Canada Computers","unverified":"Modularity and connector counts are not stated in the retailer listing. Confirm before quoting a build that needs two 8-pin PCIe connectors.","price_checked":"2026-10-06"}'::jsonb),
  ('psu-fsp-vita-1000w', 'PSU-FSP-VITA1000', 'psu-fsp-vita-1000w', 'psu', 'FSP', 'VITA 1000W 80 PLUS Gold', '1000 W Gold unit for a high-draw card, or for a build meant to take a bigger one later.', 19999, null, 5, 3, null, 'published', 'sample', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 1000, '80 PLUS Gold', 'atx', null, null, null, null, null, null, null, null, null, null, null, '{"source":"Canada Computers","unverified":"Modularity and connector counts are not stated in the retailer listing. Confirm before quoting a build that needs a 12V-2x6 connector.","price_checked":"2026-10-06"}'::jsonb),
  ('case-asus-proart-pa602', 'CASE-ASU-PA602', 'case-asus-proart-pa602', 'case', 'ASUS', 'ProArt PA602 E-ATX', 'Large workstation case. Takes E-ATX boards, a 440 mm card and a 420 mm radiator, and ships with two 200 mm front fans.', 37999, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, array['e-atx', 'atx', 'micro-atx', 'mini-itx']::form_factor[], null, null, null, null, null, null, null, null, 'atx', null, 440, null, 185, array[120, 140, 240, 280, 360, 420], null, null, null, null, null, null, '{"included_fans":"2 x 200 mm front, 1 x 140 mm rear","psu_clearance_mm":190,"radiator_detail":"Up to 420 mm","board_support":"Mini-DTX, DTX, Mini-ITX, Micro-ATX, ATX, E-ATX up to 12 x 10.9 in","source":"Canada Computers (price), ASUS techspec (clearances)","price_checked":"2026-10-06"}'::jsonb),
  ('case-asus-tuf-gt302-argb', 'CASE-ASU-GT302', 'case-asus-tuf-gt302-argb', 'case', 'ASUS', 'TUF Gaming GT302 ARGB', 'Mid-tower with four 140 mm ARGB fans fitted. Takes a 407 mm card, but the 165 mm cooler limit rules out the tallest air towers.', 20999, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, array['e-atx', 'atx', 'micro-atx', 'mini-itx']::form_factor[], null, null, null, null, null, null, null, null, 'atx', null, 407, null, 165, array[120, 140, 240, 280, 360], null, null, null, null, null, null, '{"included_fans":"3 x 140 mm ARGB front, 1 x 140 mm ARGB rear","psu_clearance_mm":220,"radiator_detail":"Top up to 360 mm, front up to 280 mm, rear 140 mm","source":"Canada Computers (price), ASUS techspec (clearances)","price_checked":"2026-10-06"}'::jsonb),
  ('fan-bequiet-light-wings-lx-120-3pack', 'FAN-BQ-LWLX120X3', 'fan-bequiet-light-wings-lx-120-3pack', 'case-fan', 'be quiet!', 'Light Wings LX 120mm PWM ARGB, 3-pack', 'Three 120 mm ARGB fans from a brand that builds its reputation on noise. The usual choice when the machine sits on the desk rather than under it.', 7499, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, 6, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"size_mm":120,"pack_quantity":3,"lighting":"ARGB","control":"PWM","source":"Canada Computers","sale_price_observed":"$39.99 on 2026-10-06","price_checked":"2026-10-06"}'::jsonb),
  ('fan-asus-tuf-tf120-argb-3pack', 'FAN-ASU-TF120X3', 'fan-asus-tuf-tf120-argb-3pack', 'case-fan', 'ASUS', 'TUF Gaming TF120 ARGB 3-in-1, 3-pack', 'Three 120 mm ARGB fans with daisy-chained cabling, which keeps the back of the case tidier than three separate runs.', 8999, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, 6, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"size_mm":120,"pack_quantity":3,"lighting":"ARGB","control":"PWM","source":"Canada Computers","sale_price_observed":"$64.99 on 2026-10-06","price_checked":"2026-10-06"}'::jsonb),
  ('fan-corsair-rs360-ii-argb-3pack', 'FAN-COR-RS360X3', 'fan-corsair-rs360-ii-argb-3pack', 'case-fan', 'Corsair', 'RS360 II ARGB 120mm, 3-pack', 'Three 120 mm ARGB fans. A straightforward set for filling the front of a mid-tower.', 7499, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, 6, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"size_mm":120,"pack_quantity":3,"lighting":"ARGB","control":"PWM","source":"Canada Computers","price_checked":"2026-10-06"}'::jsonb)
on conflict (id) do nothing;
