-- ===========================================================================
-- PC Builders Canada - development seed data
-- ===========================================================================
-- GENERATED FILE - do not edit by hand.
-- Source: src/lib/catalog/sample-catalog.ts
-- Regenerate with: npm run db:seed:generate
--
-- Each row carries its OWN data_confidence, copied from the source catalogue.
--
--   'verified' - price and compatibility-critical fields were read from a
--                retailer or manufacturer listing. The date is in
--                specs.price_checked.
--   'sample'   - at least one figure is unconfirmed. specs.unverified names
--                which one, and the storefront prints that caveat.
--
-- Prices are retail as observed on the check date, not a margin model.
-- cost_cents is null throughout because there is no distributor pricing yet,
-- and inventing one would produce a fake margin column in the admin.
--
-- Stock quantities are nominal opening figures so the storefront is usable.
-- They are NOT real counts. Set them from /admin/inventory against what is
-- actually on the shelf before trading.
--
-- Every row seeds as condition = 'new'. Refurbished and open-box units are
-- entered through /admin/components, where the condition notes are required,
-- because those notes describe one specific physical unit.
-- ===========================================================================

insert into components (
  id,
  sku,
  slug,
  category,
  brand,
  model,
  description,
  price_cents,
  cost_cents,
  stock_quantity,
  low_stock_threshold,
  image_url,
  status,
  data_confidence,
  condition,
  condition_notes,
  socket,
  supported_sockets,
  chipset,
  memory_slots,
  max_memory_gb,
  m2_slots,
  sata_ports,
  form_factor,
  supported_form_factors,
  memory_type,
  memory_capacity_gb,
  memory_modules,
  memory_speed_mts,
  tdp_watts,
  recommended_psu_watts,
  psu_wattage,
  psu_efficiency,
  psu_form_factor,
  gpu_length_mm,
  max_gpu_length_mm,
  cooler_height_mm,
  max_cooler_height_mm,
  radiator_support_mm,
  radiator_size_mm,
  cooler_type,
  cooling_capacity_watts,
  storage_interface,
  storage_capacity_gb,
  pcie_version,
  specs
) values
  ('cpu-amd-ryzen-5-7600x', 'CPU-AMD-7600X', 'cpu-amd-ryzen-5-7600x', 'cpu', 'AMD', 'Ryzen 5 7600X', 'Six-core AM5 processor for 1080p and 1440p gaming. A sensible floor for a new system that still leaves an upgrade path on the AM5 socket.', 20988, null, 5, 3, null, 'published', 'verified', 'new', null, 'AM5', null, null, null, null, null, null, null, null, 'ddr5', null, null, null, 105, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"cores":6,"threads":12,"integrated_graphics":true,"cooler_included":false,"price_checked":"2026-09-18"}'::jsonb),
  ('cpu-amd-ryzen-7-7800x3d', 'CPU-AMD-7800X3D', 'cpu-amd-ryzen-7-7800x3d', 'cpu', 'AMD', 'Ryzen 7 7800X3D', 'Eight-core AM5 processor with stacked cache. Aimed at high-framerate gaming, where cache-sensitive titles benefit most.', 60999, null, 5, 3, null, 'published', 'verified', 'new', null, 'AM5', null, null, null, null, null, null, null, null, 'ddr5', null, null, null, 120, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"cores":8,"threads":16,"cache":"104 MB total, 3D V-Cache","integrated_graphics":true,"price_checked":"2026-09-18"}'::jsonb),
  ('cpu-amd-ryzen-7-9800x3d', 'CPU-AMD-9800X3D', 'cpu-amd-ryzen-7-9800x3d', 'cpu', 'AMD', 'Ryzen 7 9800X3D', 'Current-generation eight-core AM5 gaming processor with stacked cache. The default choice in most high-framerate gaming builds.', 68900, null, 5, 3, null, 'published', 'verified', 'new', null, 'AM5', null, null, null, null, null, null, null, null, 'ddr5', null, null, null, 120, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"cores":8,"threads":16,"cache":"104 MB total, second-generation 3D V-Cache","integrated_graphics":true,"price_checked":"2026-09-18"}'::jsonb),
  ('cpu-amd-ryzen-9-9950x', 'CPU-AMD-9950X', 'cpu-amd-ryzen-9-9950x', 'cpu', 'AMD', 'Ryzen 9 9950X', 'Sixteen-core AM5 processor for rendering, compilation and multi-track production, where core count is the bottleneck.', 89900, null, 5, 3, null, 'published', 'verified', 'new', null, 'AM5', null, null, null, null, null, null, null, null, 'ddr5', null, null, null, 170, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"cores":16,"threads":32,"integrated_graphics":true,"price_checked":"2026-09-18"}'::jsonb),
  ('cpu-intel-core-ultra-5-245k', 'CPU-INT-U5245K', 'cpu-intel-core-ultra-5-245k', 'cpu', 'Intel', 'Core Ultra 5 245K', 'Mid-range LGA1851 processor for mixed gaming and productivity, with integrated graphics for troubleshooting without a card fitted.', 28999, null, 5, 3, null, 'published', 'verified', 'new', null, 'LGA1851', null, null, null, null, null, null, null, null, 'ddr5', null, null, null, 125, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"cores":"14 (6P + 8E)","integrated_graphics":true,"max_turbo_power_watts":159,"price_checked":"2026-09-18"}'::jsonb),
  ('cpu-intel-core-ultra-7-265k', 'CPU-INT-U7265K', 'cpu-intel-core-ultra-7-265k', 'cpu', 'Intel', 'Core Ultra 7 265K', 'Twenty-core LGA1851 processor balancing gaming performance against heavily threaded creative work.', 47999, null, 5, 3, null, 'published', 'verified', 'new', null, 'LGA1851', null, null, null, null, null, null, null, null, 'ddr5', null, null, null, 125, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"cores":"20 (8P + 12E)","integrated_graphics":true,"price_checked":"2026-09-18"}'::jsonb),
  ('cpu-intel-core-ultra-9-285k', 'CPU-INT-U9285K', 'cpu-intel-core-ultra-9-285k', 'cpu', 'Intel', 'Core Ultra 9 285K', 'Flagship LGA1851 processor for workstation duty: simulation, rendering and large compile jobs.', 89999, null, 5, 3, null, 'published', 'verified', 'new', null, 'LGA1851', null, null, null, null, null, null, null, null, 'ddr5', null, null, null, 125, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"cores":"24 (8P + 16E)","integrated_graphics":true,"chipset_support":"B860, H810, H870, Z890","price_checked":"2026-09-18"}'::jsonb),
  ('mb-msi-mag-x870-tomahawk', 'MB-MSI-X870TOMA', 'mb-msi-mag-x870-tomahawk', 'motherboard', 'MSI', 'MAG X870 TOMAHAWK WIFI', 'ATX AM5 board for high-core-count Ryzen builds, with heavy VRM cooling, Wi-Fi 7 and four M.2 slots.', 38999, null, 5, 3, null, 'published', 'verified', 'new', null, 'AM5', null, 'X870', 4, 256, 4, 4, 'atx', null, 'ddr5', null, null, null, 55, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"wifi":"Wi-Fi 7","lan":"5 Gbps","m2_detail":"2x PCIe 5.0 x4, 2x PCIe 4.0","price_checked":"2026-09-18"}'::jsonb),
  ('mb-asus-rog-strix-b850-f', 'MB-ASU-B850F', 'mb-asus-rog-strix-b850-f', 'motherboard', 'ASUS', 'ROG STRIX B850-F GAMING WIFI', 'ATX AM5 board with PCIe 5.0 graphics and storage support, strong power delivery and Wi-Fi 7.', 41999, null, 5, 3, null, 'published', 'sample', 'new', null, 'AM5', null, 'B850', 4, 192, 4, 4, 'atx', null, 'ddr5', null, null, null, 50, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"wifi":"Wi-Fi 7","lan":"Intel 2.5 Gbps","power_stages":"16+2+2","unverified":"SATA port count not stated by the retailer","price_checked":"2026-09-18"}'::jsonb),
  ('mb-asus-rog-strix-b850-i', 'MB-ASU-B850I', 'mb-asus-rog-strix-b850-i', 'motherboard', 'ASUS', 'ROG STRIX B850-I GAMING WIFI', 'Mini-ITX AM5 board for compact builds. Two memory slots, dense layout, PCIe 5.0 graphics slot.', 48999, null, 5, 3, null, 'published', 'sample', 'new', null, 'AM5', null, 'B850', 2, 96, 2, 2, 'mini-itx', null, 'ddr5', null, null, null, 40, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"wifi":"Wi-Fi 7","lan":"2.5 Gbps","power_stages":"10+2+1","unverified":"SATA port count not stated by the retailer","price_checked":"2026-09-18"}'::jsonb),
  ('mb-gigabyte-b860-aorus-elite', 'MB-GIG-B860ELITE', 'mb-gigabyte-b860-aorus-elite', 'motherboard', 'Gigabyte', 'B860 AORUS ELITE WIFI7 ICE', 'ATX LGA1851 board with Wi-Fi 7 and three M.2 slots, for mid-range Intel Core Ultra builds.', 30999, null, 5, 3, null, 'published', 'sample', 'new', null, 'LGA1851', null, 'B860', 4, 256, 3, 4, 'atx', null, 'ddr5', null, null, null, 45, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"wifi":"Wi-Fi 7","lan":"2.5 GbE","unverified":"SATA port count not stated by the retailer","price_checked":"2026-09-18"}'::jsonb),
  ('mb-msi-mpg-z890-carbon', 'MB-MSI-Z890CARBON', 'mb-msi-mpg-z890-carbon', 'motherboard', 'MSI', 'MPG Z890 CARBON WIFI', 'Enthusiast ATX LGA1851 board with five M.2 slots and Thunderbolt-class connectivity, for workstation builds.', 74999, null, 5, 3, null, 'published', 'sample', 'new', null, 'LGA1851', null, 'Z890', 4, 256, 5, 4, 'atx', null, 'ddr5', null, null, null, 55, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"wifi":"Wi-Fi 7","lan":"Killer 5G","unverified":"SATA port count and maximum memory not stated by the retailer","price_checked":"2026-09-18"}'::jsonb),
  ('cool-deepcool-ak620-g2', 'COOL-DC-AK620G2', 'cool-deepcool-ak620-g2', 'cooler', 'DeepCool', 'AK620 G2', 'Dual-tower air cooler with six heat pipes and two 120 mm fans. Handles mid-range and most high-end processors without a pump to fail.', 7999, null, 5, 3, null, 'published', 'verified', 'new', null, null, array['AM5', 'AM4', 'LGA1851', 'LGA1700', 'LGA1200', 'LGA1151'], null, null, null, null, null, null, null, null, null, null, null, 5, null, null, null, null, null, null, 159, null, null, null, 'air', 260, null, null, null, '{"fans":2,"fan_size_mm":120,"heat_pipes":6,"airflow_cfm":57.76,"price_checked":"2026-09-18"}'::jsonb),
  ('cool-arctic-liquid-freezer-iii-360', 'COOL-ARC-LF3-360', 'cool-arctic-liquid-freezer-iii-360', 'cooler', 'Arctic', 'Liquid Freezer III 360', '360 mm all-in-one liquid cooler with three 120 mm fans. Strong thermal headroom for high-power processors.', 18999, null, 5, 3, null, 'published', 'sample', 'new', null, null, array['AM5', 'AM4', 'LGA1851', 'LGA1700'], null, null, null, null, null, null, null, null, null, null, null, 12, null, null, null, null, null, null, null, null, null, array[360], 'aio', null, null, null, null, '{"fans":3,"fan_size_mm":120,"fan_rpm":"200-1800","unverified":"Socket bracket list not stated by the retailer","price_checked":"2026-09-18"}'::jsonb),
  ('ram-xpg-lancer-blade-16gb-ddr5-5600', 'RAM-XPG-16G5600', 'ram-xpg-lancer-blade-16gb-ddr5-5600', 'ram', 'XPG', 'Lancer Blade RGB 16GB (2x8GB) DDR5-5600', 'Entry DDR5 kit for office systems and light gaming.', 30999, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, 'ddr5', 16, 2, 5600, 8, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"cas_latency":"CL46","form":"UDIMM","price_checked":"2026-09-18"}'::jsonb),
  ('ram-lexar-thor-32gb-ddr5-6000', 'RAM-LEX-32G6000', 'ram-lexar-thor-32gb-ddr5-6000', 'ram', 'Lexar', 'THOR OC 32GB (2x16GB) DDR5-6000', 'The value 32 GB kit. Two modules at 6000 MT/s, leaving two slots free on a four-slot board.', 56999, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, 'ddr5', 32, 2, 6000, 10, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"cas_latency":"CL36","form":"UDIMM","price_checked":"2026-09-18"}'::jsonb),
  ('ram-teamgroup-vulcan-32gb-ddr5-6000', 'RAM-TEA-32G6000', 'ram-teamgroup-vulcan-32gb-ddr5-6000', 'ram', 'TEAMGROUP', 'T-FORCE VULCAN 32GB (2x16GB) DDR5-6000 CL30', 'Low-latency 32 GB kit. CL30 at 6000 MT/s is the sweet spot for cache-sensitive gaming processors.', 73999, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, 'ddr5', 32, 2, 6000, 10, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"cas_latency":"CL30","form":"UDIMM","price_checked":"2026-09-18"}'::jsonb),
  ('ram-teamgroup-delta-64gb-ddr5-6000', 'RAM-TEA-64G6000', 'ram-teamgroup-delta-64gb-ddr5-6000', 'ram', 'TEAMGROUP', 'T-FORCE DELTA RGB 64GB (2x32GB) DDR5-6000 CL30', 'High-capacity dual-module kit for workstation duty: large project files, virtual machines, multi-application workloads.', 148999, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, 'ddr5', 64, 2, 6000, 12, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"cas_latency":"CL30","form":"UDIMM","price_checked":"2026-09-18"}'::jsonb),
  ('gpu-msi-rtx-5060-ti-16g', 'GPU-MSI-5060TI16', 'gpu-msi-rtx-5060-ti-16g', 'gpu', 'MSI', 'GeForce RTX 5060 Ti 16G VENTUS 3X OC', '1080p and 1440p card with 16 GB of memory, which matters more than raw speed in newer titles.', 114999, null, 5, 3, null, 'published', 'sample', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, 180, 600, null, null, null, 306, null, null, null, null, null, null, null, null, null, 5, '{"vram_gb":16,"memory":"GDDR7 128-bit","power_connectors":"1x 8-pin","cuda_cores":4608,"unverified":"Board power and recommended PSU taken from the NVIDIA reference figures","price_checked":"2026-09-18"}'::jsonb),
  ('gpu-sapphire-rx-9070-xt', 'GPU-SAP-9070XT', 'gpu-sapphire-rx-9070-xt', 'gpu', 'SAPPHIRE', 'PULSE Radeon RX 9070 XT 16GB', 'AMD 1440p and 4K card with 16 GB of memory and a triple-fan cooler. The value choice at this tier.', 124999, null, 5, 3, null, 'published', 'sample', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, 304, 850, null, null, null, 320, null, null, null, null, null, null, null, null, null, 5, '{"vram_gb":16,"memory":"GDDR6 256-bit","stream_processors":4096,"dimensions_mm":"320 x 120.25 x 61.6","unverified":"Board power taken from the AMD reference figure","price_checked":"2026-09-18"}'::jsonb),
  ('gpu-gigabyte-rtx-5080-gaming-oc', 'GPU-GIG-5080GOC', 'gpu-gigabyte-rtx-5080-gaming-oc', 'gpu', 'Gigabyte', 'GeForce RTX 5080 GAMING OC 16GB', '4K gaming card and a strong option for GPU-accelerated creative work. Long and heavy, so check case clearance.', 239900, null, 5, 3, null, 'published', 'sample', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, 360, 850, null, null, null, 340, null, null, null, null, null, null, null, null, null, 5, '{"vram_gb":16,"memory":"GDDR7 256-bit, 30 Gbps","dimensions_mm":"340 x 140 x 70","cooling":"WINDFORCE triple fan","unverified":"Board power taken from the NVIDIA reference figure","price_checked":"2026-09-18"}'::jsonb),
  ('ssd-kingston-nv3-1tb', 'SSD-KIN-NV31T', 'ssd-kingston-nv3-1tb', 'storage', 'Kingston', 'NV3 1TB NVMe', 'Value M.2 NVMe drive. Enough for the operating system and a working set of games.', 21999, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, 6, null, null, null, null, null, null, null, null, null, null, null, null, 'nvme-m2', 1000, 4, '{"form_factor":"M.2 2280","price_checked":"2026-09-18"}'::jsonb),
  ('ssd-wd-black-sn850x-1tb', 'SSD-WD-SN850X1T', 'ssd-wd-black-sn850x-1tb', 'storage', 'Western Digital', 'WD_BLACK SN850X 1TB NVMe', 'Fast M.2 NVMe drive with a DRAM cache. A good single-drive boot and game library option.', 31999, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, 7, null, null, null, null, null, null, null, null, null, null, null, null, 'nvme-m2', 1000, 4, '{"form_factor":"M.2 2280","dram_cache":true,"price_checked":"2026-09-18"}'::jsonb),
  ('ssd-wd-black-sn850x-2tb', 'SSD-WD-SN850X2T', 'ssd-wd-black-sn850x-2tb', 'storage', 'Western Digital', 'WD_BLACK SN850X 2TB NVMe', 'High-performance 2 TB M.2 drive. The default boot drive for gaming and workstation builds.', 52999, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, 8, null, null, null, null, null, null, null, null, null, null, null, null, 'nvme-m2', 2000, 4, '{"form_factor":"M.2 2280","dram_cache":true,"price_checked":"2026-09-18"}'::jsonb),
  ('ssd-wd-black-sn7100-4tb', 'SSD-WD-SN71004T', 'ssd-wd-black-sn7100-4tb', 'storage', 'Western Digital', 'WD_BLACK SN7100 4TB NVMe', 'High-capacity M.2 drive for project files and large game libraries, at a lower cost per terabyte.', 72999, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, 7, null, null, null, null, null, null, null, null, null, null, null, null, 'nvme-m2', 4000, 4, '{"form_factor":"M.2 2280","price_checked":"2026-09-18"}'::jsonb),
  ('psu-deepcool-pn650m', 'PSU-DC-PN650M', 'psu-deepcool-pn650m', 'psu', 'DeepCool', 'PN650M 650W Gold', 'Fully modular 650 W ATX 3.1 unit for office builds and lower-power gaming systems.', 8988, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 650, '80 PLUS Gold', 'atx', null, null, null, null, null, null, null, null, null, null, null, '{"modular":"Fully modular","atx_version":"ATX 3.1","price_checked":"2026-09-18"}'::jsonb),
  ('psu-deepcool-pn750m', 'PSU-DC-PN750M', 'psu-deepcool-pn750m', 'psu', 'DeepCool', 'PN750M 750W Gold', 'Fully modular 750 W ATX 3.1 unit. A sensible match for mid-range gaming builds.', 9988, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 750, '80 PLUS Gold', 'atx', null, null, null, null, null, null, null, null, null, null, null, '{"modular":"Fully modular","atx_version":"ATX 3.1","price_checked":"2026-09-18"}'::jsonb),
  ('psu-deepcool-pn850m', 'PSU-DC-PN850M', 'psu-deepcool-pn850m', 'psu', 'DeepCool', 'PN850M 850W Gold', 'Fully modular 850 W ATX 3.1 unit, sized for builds with a higher-power graphics card.', 11488, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 850, '80 PLUS Gold', 'atx', null, null, null, null, null, null, null, null, null, null, null, '{"modular":"Fully modular","atx_version":"ATX 3.1","price_checked":"2026-09-18"}'::jsonb),
  ('psu-deepcool-pn1000m', 'PSU-DC-PN1000M', 'psu-deepcool-pn1000m', 'psu', 'DeepCool', 'PN1000M 1000W Gold', 'Fully modular 1000 W ATX 3.1 unit with the 12V-2x6 connector current high-power cards expect.', 13988, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 1000, '80 PLUS Gold', 'atx', null, null, null, null, null, null, null, null, null, null, null, '{"modular":"Fully modular","atx_version":"ATX 3.1","price_checked":"2026-09-18"}'::jsonb),
  ('psu-gigabyte-ud1300gm', 'PSU-GIG-UD1300GM', 'psu-gigabyte-ud1300gm', 'psu', 'Gigabyte', 'UD1300GM PG5 1300W Gold', 'High-capacity unit for flagship graphics cards and high-core-count workstations that run long jobs.', 32999, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 1300, '80 PLUS Gold', 'atx', null, null, null, null, null, null, null, null, null, null, null, '{"modular":"Fully modular","price_checked":"2026-09-18"}'::jsonb),
  ('case-nzxt-h5-flow', 'CASE-NZX-H5FLOW', 'case-nzxt-h5-flow', 'case', 'NZXT', 'H5 Flow Compact ATX Mid-Tower', 'Compact ATX case with a perforated front panel and straightforward cable routing. Good value at the entry tier.', 9999, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, array['atx', 'micro-atx', 'mini-itx']::form_factor[], null, null, null, null, null, null, null, null, 'atx', null, 410, null, 170, array[240, 360], null, null, null, null, null, null, '{"front_panel":"Perforated steel","psu_clearance_mm":200,"radiator_detail":"Front 360 mm, top 240 mm","price_checked":"2026-09-18"}'::jsonb),
  ('case-corsair-frame-4000d-rs', 'CASE-COR-FRAME4000D', 'case-corsair-frame-4000d-rs', 'case', 'Corsair', 'FRAME 4000D RS', 'Mid-tower with a high-airflow panel and a clean cable channel. A dependable default for most builds.', 10499, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, array['e-atx', 'atx', 'micro-atx', 'mini-itx']::form_factor[], null, null, null, null, null, null, null, null, 'atx', null, 430, null, 170, array[240, 280, 360], null, null, null, null, null, null, '{"radiator_detail":"Front, top and side all take 240/280/360 mm; rear 120/140 mm","price_checked":"2026-09-18"}'::jsonb),
  ('case-lian-li-o11d-evo-rgb', 'CASE-LL-O11DEVORGB', 'case-lian-li-o11d-evo-rgb', 'case', 'Lian Li', 'O11D EVO RGB Mid-Tower', 'Dual-chamber showcase case with wide radiator support and room for the longest cards. The usual choice for builds meant to be looked at.', 23999, null, 5, 3, null, 'published', 'sample', 'new', null, null, null, null, null, null, null, null, null, array['e-atx', 'atx', 'micro-atx', 'mini-itx']::form_factor[], null, null, null, null, null, null, null, null, 'atx', null, 455, null, 167, array[240, 280, 360, 420], null, null, null, null, null, null, '{"layout":"Dual chamber","radiator_detail":"Top 240/360/420 mm with bracket; side and bottom 240/280/360 mm","psu_clearance_mm":220,"unverified":"Full motherboard form factor list not stated by the retailer","price_checked":"2026-09-18"}'::jsonb),
  ('os-none', 'OS-NONE', 'os-none', 'os', 'PC Builders Canada', 'No operating system', 'Ships without an OS installed. Choose this if you are supplying your own licence or installing Linux yourself.', 0, null, 999, 0, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"note":"The system is still tested before shipping, using our own bootable media."}'::jsonb),
  ('os-windows-11-home', 'OS-MS-W11HOME', 'os-windows-11-home', 'os', 'Microsoft', 'Windows 11 Home', 'Windows 11 Home licence, installed and updated before the system ships.', 15900, null, 999, 10, null, 'published', 'sample', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"edition":"Home","delivery":"Pre-installed and activated","unverified":"Price is a placeholder. OEM licence cost depends on your Microsoft reseller account, not retail."}'::jsonb),
  ('os-windows-11-pro', 'OS-MS-W11PRO', 'os-windows-11-pro', 'os', 'Microsoft', 'Windows 11 Pro', 'Windows 11 Pro licence. Adds BitLocker, Remote Desktop host and domain join, the usual requirements for a work machine.', 23900, null, 999, 10, null, 'published', 'sample', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"edition":"Pro","delivery":"Pre-installed and activated","unverified":"Price is a placeholder. OEM licence cost depends on your Microsoft reseller account, not retail."}'::jsonb),
  ('net-tplink-tl-sg108e', 'NET-TPL-SG108E', 'net-tplink-tl-sg108e', 'networking', 'TP-Link', 'TL-SG108E 8-Port Gigabit Easy Smart Switch', 'Eight gigabit ports with VLAN, QoS and IGMP snooping in a fanless metal case. The usual starting point when a flat home network needs segmenting without moving to a full managed stack.', 3999, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"ports":"8 x 1GbE RJ45","management":"Web-managed (Easy Smart)","vlan":"Port-based, tag-based and MTU VLAN","qos":"Yes, with IGMP snooping","jumbo_frame":"15K","cooling":"Fanless","mounting":"Desktop or wall","price_checked":"2026-09-27","sale_price_observed":"$34.99 on 2026-09-27","source":"Canada Computers"}'::jsonb),
  ('net-tplink-tl-sg108pe', 'NET-TPL-SG108PE', 'net-tplink-tl-sg108pe', 'networking', 'TP-Link', 'TL-SG108PE 8-Port Gigabit PoE+ Easy Smart Switch', 'The same eight gigabit ports as the SG108E, with four of them supplying PoE+ across a 64 W budget. Enough to run a pair of access points and a couple of cameras without separate power bricks.', 8999, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"ports":"8 x 1GbE RJ45","poe_ports":"4 x PoE+ (802.3af/at)","poe_budget_watts":64,"management":"Web-managed (Easy Smart)","vlan":"Port-based, tag-based and MTU VLAN","price_checked":"2026-09-27","source":"Canada Computers"}'::jsonb),
  ('net-ubiquiti-usw-flex-2-5g-5', 'NET-UBI-FLEX25G5', 'net-ubiquiti-usw-flex-2-5g-5', 'networking', 'Ubiquiti', 'UniFi USW-Flex-2.5G-5', 'Five 2.5GbE ports, managed through UniFi. The sensible upgrade once a NAS and a desktop both have 2.5G and a gigabit switch has become the bottleneck between them.', 7999, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"ports":"5 x 2.5GbE RJ45","switching":"Layer 2, IGMP snooping, port mirroring, spanning tree","management":"UniFi Network application","form_factor":"Desktop","price_checked":"2026-09-27","source":"Canada Computers","availability_note":"Was sold out online at the retailer on the check date; confirm supply before promising a ship date."}'::jsonb),
  ('net-ubiquiti-usw-flex-2-5g-8-poe', 'NET-UBI-FLEX25G8P', 'net-ubiquiti-usw-flex-2-5g-8-poe', 'networking', 'Ubiquiti', 'UniFi USW-Flex-2.5G-8-PoE', 'Eight-port PoE switch with a 10 GbE RJ45/SFP+ combination uplink, in a desktop shell meant for deployment outside a wiring closet. That uplink is the reason to pick it over a cheaper eight-port unit.', 28500, null, 5, 3, null, 'published', 'sample', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"ports":"8 ports, all PoE+ capable","uplink":"1 x 10GbE RJ45 / SFP+ combination","management":"UniFi Network application","dimensions_mm":"99.6 x 163.7 x 31.7","price_checked":"2026-09-27","source":"Canada Computers","unverified":"Port speed and total PoE budget. The retailer listing described the access ports as 10/100/1000 while naming the model 2.5G, and gave no PoE wattage at all. Confirm both against Ubiquiti documentation before publishing this row.","availability_note":"Sold out online and in store at the retailer on the check date."}'::jsonb),
  ('nas-synology-ds224-plus', 'NAS-SYN-DS224P', 'nas-synology-ds224-plus', 'nas', 'Synology', 'DiskStation DS224+ (2-bay, diskless)', 'Two-bay DiskStation running DSM. Diskless, so pair it with a couple of NAS-rated drives in a mirror. The common first NAS for household backups, Time Machine targets and a media library.', 44999, null, 5, 3, null, 'published', 'sample', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"bays":2,"drive_support":"SATA HDD or SSD, 3.5 inch or 2.5 inch","memory":"2 GB DDR4","network":"2 x 1GbE RJ45","usb":"2 x USB 3.2 Gen 1","power_draw_watts":15,"supplied":"Diskless - drives sold separately","price_checked":"2026-09-27","source":"Canada Computers","unverified":"Exact CPU model and maximum raw capacity. The retailer listing said only \"Intel Celeron 2 GHz\" and described the bays as SAS, which is wrong for this unit. Confirm against the Synology datasheet before publishing this row."}'::jsonb),
  ('nas-synology-ds423-plus', 'NAS-SYN-DS423P', 'nas-synology-ds423-plus', 'nas', 'Synology', 'DiskStation DS423+ (4-bay, diskless)', 'Four-bay DiskStation with two M.2 NVMe slots for read and write cache. Four bays is the point where you can run a single-drive-redundant array and still grow it, which two bays never really allows.', 74999, null, 5, 3, null, 'published', 'sample', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"bays":4,"drive_support":"SATA HDD or SSD, 3.5 inch or 2.5 inch","cache_slots":"2 x M.2 2280 NVMe","memory":"2 GB DDR4","network":"2 x 1GbE RJ45","usb":"2 x USB 3.2 Gen 1","max_raw_capacity":"Up to 72 TB per the retailer listing","dimensions_mm":"166 x 199 x 223","supplied":"Diskless - drives sold separately","price_checked":"2026-09-27","source":"Canada Computers","unverified":"Exact CPU model, and the 72 TB maximum capacity figure. Both came from retailer copy rather than the Synology datasheet."}'::jsonb),
  ('hdd-wd-red-plus-8tb', 'HDD-WD-RED8TB', 'hdd-wd-red-plus-8tb', 'storage', 'Western Digital', 'WD Red Plus 8TB NAS HDD (WD80EFPX)', 'Eight terabytes of CMR NAS storage rated for 180 TB a year and continuous operation. CMR rather than SMR is the point: shingled drives behave badly during a RAID rebuild, which is exactly when you need them not to.', 50999, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'sata', 8000, null, '{"rpm":5640,"cache_mb":256,"recording":"CMR","form_factor":"3.5 inch","workload_rating":"180 TB per year","warranty":"3-year limited","nas_rated":true,"price_checked":"2026-09-27","source":"Canada Computers"}'::jsonb),
  ('hdd-seagate-ironwolf-4tb', 'HDD-SEA-IW4TB', 'hdd-seagate-ironwolf-4tb', 'storage', 'Seagate', 'IronWolf 4TB NAS HDD (ST4000VN006)', 'Four terabytes rated for 24/7 NAS duty, with three years of Rescue data recovery included. A reasonable capacity per dollar for a first two-bay mirror.', 27999, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'sata', 4000, null, '{"rpm":5400,"cache_mb":256,"form_factor":"3.5 inch","duty":"Rated for 24x7 operation","included":"3 years Rescue Data Recovery Services","warranty":"3-year limited","nas_rated":true,"price_checked":"2026-09-27","sale_price_observed":"$264.99 on 2026-09-27","source":"Canada Computers","availability_note":"Sold out online at the retailer on the check date; limited store stock."}'::jsonb),
  ('mini-rpi5-4gb', 'MINI-RPI5-4GB', 'mini-rpi5-4gb', 'mini-pc', 'Raspberry Pi', 'Raspberry Pi 5 / 4GB', 'The 4 GB Pi 5. Enough for Pi-hole, Home Assistant, a print server or a light Docker host. It needs a power supply, storage and cooling, none of which are in the box.', 15395, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"soc":"Broadcom BCM2712, quad-core Cortex-A76 at 2.4 GHz","memory":"4 GB LPDDR4X-4267","gpu":"VideoCore VII","network":"Gigabit Ethernet (PoE+ with HAT), Wi-Fi 802.11ac, Bluetooth 5.0","usb":"2 x USB 3.0, 2 x USB 2.0","display":"Dual 4Kp60 micro HDMI","expansion":"PCIe 2.0 x1, 40-pin GPIO, microSD","power_input":"5V/5A USB-C Power Delivery","supplied":"Board only","sbc_accessory":false,"price_checked":"2026-09-27","source":"PiShop.ca"}'::jsonb),
  ('mini-rpi5-8gb', 'MINI-RPI5-8GB', 'mini-rpi5-8gb', 'mini-pc', 'Raspberry Pi', 'Raspberry Pi 5 / 8GB', 'The 8 GB Pi 5, and the version to pick if it will run several containers at once or double as a small desktop. Roughly three times the CPU throughput of a Pi 4.', 24495, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"soc":"Broadcom BCM2712, quad-core Cortex-A76 at 2.4 GHz","memory":"8 GB LPDDR4X-4267","gpu":"VideoCore VII, OpenGL ES 3.1 and Vulkan 1.2","network":"Gigabit Ethernet (PoE+ with HAT), Wi-Fi 802.11ac, Bluetooth 5.0","usb":"2 x USB 3.0 (5 Gbps), 2 x USB 2.0","display":"Dual 4Kp60 micro HDMI with HDR","expansion":"PCIe 2.0 x1, 40-pin GPIO, microSD, real-time clock","power_input":"5V/5A USB-C Power Delivery","supplied":"Board only","sbc_accessory":false,"price_checked":"2026-09-27","source":"PiShop.ca"}'::jsonb),
  ('mini-rpi5-16gb', 'MINI-RPI5-16GB', 'mini-rpi5-16gb', 'mini-pc', 'Raspberry Pi', 'Raspberry Pi 5 / 16GB', 'The 16 GB Pi 5, for a workload that actually needs the memory rather than the cores: a larger container stack, a self-hosted database, or compiling on the board itself.', 42695, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"soc":"Broadcom BCM2712, quad-core Cortex-A76 at 2.4 GHz","memory":"16 GB LPDDR4X-4267","gpu":"VideoCore VII, OpenGL ES 3.1 and Vulkan 1.2","network":"Gigabit Ethernet (PoE+ with HAT), Wi-Fi 802.11ac, Bluetooth 5.0","usb":"2 x USB 3.0 (5 Gbps), 2 x USB 2.0","display":"Dual 4Kp60 micro HDMI with HDR","expansion":"PCIe 2.0 x1, 2 x 4-lane MIPI, 40-pin GPIO, microSD, real-time clock","power_input":"5V/5A USB-C Power Delivery","supplied":"Board only","sbc_accessory":false,"price_checked":"2026-09-27","source":"PiShop.ca"}'::jsonb),
  ('mini-rpi5-desktop-kit', 'MINI-RPI5-KIT8', 'mini-rpi5-desktop-kit', 'mini-pc', 'Raspberry Pi', 'Raspberry Pi 5 Desktop Kit (8GB)', 'A complete Pi 5 desktop in one box: board, case, official keyboard and mouse, 27 W supply, both HDMI cables, a preloaded microSD card and the beginner guide. Connect a monitor and it runs.', 28000, null, 5, 3, null, 'published', 'sample', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"includes":"Raspberry Pi 5 (8 GB), case, keyboard and mouse, 27 W USB-C PD supply, 2 x micro HDMI to HDMI 1 m, 16 GB microSD with Raspberry Pi OS, printed beginner guide","memory":"8 GB LPDDR4X-4267","sbc_accessory":false,"price_checked":"2026-09-27","source":"PiShop.ca","unverified":"The bundled microSD card is listed as carrying the 32-bit OS image. Confirm which image actually ships before advising a customer who wants 64-bit."}'::jsonb),
  ('mini-gigabyte-brix-n150', 'MINI-GB-BRIXN150', 'mini-gigabyte-brix-n150', 'mini-pc', 'GIGABYTE', 'BRIX Intel N150 Barebones', 'A barebones x86 mini PC with Wi-Fi and Bluetooth already fitted. Barebones means no memory, no drive and no operating system, so budget for all three; the payoff is choosing them yourself.', 23900, null, 5, 3, null, 'published', 'sample', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"cpu":"Intel N150","wireless":"Wi-Fi and Bluetooth included","supplied":"Barebones - no memory, storage or operating system","sbc_accessory":false,"price_checked":"2026-09-27","source":"Canada Computers","unverified":"Memory and storage slot counts, supported capacities and port layout were not stated in the retailer listing. Confirm from the GIGABYTE spec sheet before advising on an upgrade."}'::jsonb),
  ('mini-gigabyte-brix-n250', 'MINI-GB-BRIXN250', 'mini-gigabyte-brix-n250', 'mini-pc', 'GIGABYTE', 'BRIX Intel N250 Barebones', 'The N250 barebones BRIX, a step up from the N150 on the same build-it-yourself terms. A quiet always-on box for a media front end, a small server or a point-of-sale terminal.', 29900, null, 5, 3, null, 'published', 'sample', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"cpu":"Intel N250","wireless":"Wi-Fi and Bluetooth included","supplied":"Barebones - no memory, storage or operating system","sbc_accessory":false,"price_checked":"2026-09-27","sale_price_observed":"$199.00 on 2026-09-27","source":"Canada Computers","unverified":"Memory and storage slot counts, supported capacities and port layout were not stated in the retailer listing."}'::jsonb),
  ('mini-rpi-active-cooler', 'MINI-RPI-COOLER', 'mini-rpi-active-cooler', 'mini-pc', 'Raspberry Pi', 'Active Cooler for Raspberry Pi 5', 'Clip-on aluminium heatsink with a temperature-controlled blower. A Pi 5 under sustained load will throttle without active cooling, so treat this as part of the board rather than an extra.', 700, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"fits":"Raspberry Pi 5","mounting":"Clip-on, uses the board mounting points","control":"Temperature-controlled fan","sbc_accessory":true,"price_checked":"2026-09-27","source":"PiShop.ca"}'::jsonb),
  ('mini-rpi-27w-psu', 'MINI-RPI-PSU27', 'mini-rpi-27w-psu', 'mini-pc', 'Raspberry Pi', '27W USB-C Power Delivery Supply', 'The official 27 W supply. A Pi 5 raises its own USB port budget from roughly 600 mA to 1.6 A only when it detects a PD supply of this class, so a generic charger quietly costs you peripheral power.', 1695, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"output":"5.1V/5A, 9V/3A, 12V/2.25A, 15V/1.8A","connector":"USB-C Power Delivery","note":"Unlocks the higher USB port current budget on Raspberry Pi 5","sbc_accessory":true,"price_checked":"2026-09-27","source":"PiShop.ca"}'::jsonb),
  ('mini-rpi-m2-hat', 'MINI-RPI-M2HAT', 'mini-rpi-m2-hat', 'mini-pc', 'Raspberry Pi', 'M.2 HAT+ for Raspberry Pi 5', 'Brings the Pi 5 PCIe lane out to an M.2 slot, so an NVMe drive can replace the microSD card as the boot device. Around 500 MB/s, and a far longer service life than a card under constant writes.', 1695, null, 5, 3, null, 'published', 'verified', 'new', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"interface":"Single-lane PCIe 2.0","supports":"M key M.2 devices, 2230 and 2242 form factors","throughput":"Up to 500 MB/s","power_delivery":"Up to 3 A to the attached device","includes":"16 mm stacking header, threaded spacers, ribbon cable","compatibility":"Fits with the Raspberry Pi Active Cooler in place","sbc_accessory":true,"price_checked":"2026-09-27","source":"PiShop.ca"}'::jsonb)
on conflict (id) do update set
  sku = excluded.sku,
  slug = excluded.slug,
  category = excluded.category,
  brand = excluded.brand,
  model = excluded.model,
  description = excluded.description,
  price_cents = excluded.price_cents,
  cost_cents = excluded.cost_cents,
  stock_quantity = excluded.stock_quantity,
  low_stock_threshold = excluded.low_stock_threshold,
  image_url = excluded.image_url,
  status = excluded.status,
  data_confidence = excluded.data_confidence,
  condition = excluded.condition,
  condition_notes = excluded.condition_notes,
  socket = excluded.socket,
  supported_sockets = excluded.supported_sockets,
  chipset = excluded.chipset,
  memory_slots = excluded.memory_slots,
  max_memory_gb = excluded.max_memory_gb,
  m2_slots = excluded.m2_slots,
  sata_ports = excluded.sata_ports,
  form_factor = excluded.form_factor,
  supported_form_factors = excluded.supported_form_factors,
  memory_type = excluded.memory_type,
  memory_capacity_gb = excluded.memory_capacity_gb,
  memory_modules = excluded.memory_modules,
  memory_speed_mts = excluded.memory_speed_mts,
  tdp_watts = excluded.tdp_watts,
  recommended_psu_watts = excluded.recommended_psu_watts,
  psu_wattage = excluded.psu_wattage,
  psu_efficiency = excluded.psu_efficiency,
  psu_form_factor = excluded.psu_form_factor,
  gpu_length_mm = excluded.gpu_length_mm,
  max_gpu_length_mm = excluded.max_gpu_length_mm,
  cooler_height_mm = excluded.cooler_height_mm,
  max_cooler_height_mm = excluded.max_cooler_height_mm,
  radiator_support_mm = excluded.radiator_support_mm,
  radiator_size_mm = excluded.radiator_size_mm,
  cooler_type = excluded.cooler_type,
  cooling_capacity_watts = excluded.cooling_capacity_watts,
  storage_interface = excluded.storage_interface,
  storage_capacity_gb = excluded.storage_capacity_gb,
  pcie_version = excluded.pcie_version,
  specs = excluded.specs,
  updated_at = now();


-- ---------------------------------------------------------------------------
-- component_categories - display metadata, one row per category
-- ---------------------------------------------------------------------------
insert into component_categories (category, label, sort_order) values
  ('cpu', 'Processor', 10),
  ('motherboard', 'Motherboard', 20),
  ('cooler', 'CPU Cooler', 30),
  ('ram', 'Memory', 40),
  ('gpu', 'Graphics Card', 50),
  ('storage', 'Storage', 60),
  ('psu', 'Power Supply', 70),
  ('case', 'Case', 80),
  ('os', 'Operating System', 90),
  ('accessory', 'Accessories', 100),
  ('networking', 'Networking & Server', 110),
  ('nas', 'NAS & Storage Enclosure', 120),
  ('mini-pc', 'Mini PC & Single-Board', 130),
  ('case-fan', 'Case Fan', 140),
  ('monitor', 'Monitor', 150),
  ('other', 'Other', 160)
on conflict (category) do update set
  label = excluded.label,
  updated_at = now();


-- ---------------------------------------------------------------------------
-- services
-- ---------------------------------------------------------------------------
insert into services (
  id, slug, name, short_description, includes, note, price_text,
  featured, status, sort_order
) values
  ('custom-builds', 'custom-builds', 'Custom PC building', 'A machine assembled from a parts list we have checked together, cabled properly and tested before it leaves.', array['Parts list review against your workload and budget', 'Assembly with cable routing that does not block airflow', 'BIOS configuration and memory profile verification', 'Thermal and stability testing under sustained load', 'Operating system, drivers and updates if requested'], null, null, true, 'published', 10),
  ('upgrades', 'upgrades', 'PC upgrades', 'Adding or replacing parts in a machine you already own, after checking what the existing system can actually take.', array['Compatibility check against your current motherboard, case and power supply', 'Graphics card, memory, storage and cooling upgrades', 'Migration of your existing installation to a new drive where practical', 'Post-upgrade testing so the machine leaves in a known-good state'], 'We will tell you when an upgrade is not worth it. A platform at the end of its upgrade path is better replaced than fed.', null, true, 'published', 20),
  ('diagnostics', 'diagnostics', 'Hardware diagnostics', 'Finding the actual cause of instability, rather than replacing parts until the symptom moves.', array['Memory testing and storage health checks', 'Thermal behaviour under load, including throttling analysis', 'Power delivery and connection inspection', 'Component isolation testing where a fault is not obvious', 'A written summary of what was found and what we recommend'], null, null, true, 'published', 30),
  ('windows', 'windows', 'Windows installation', 'A clean installation, configured and updated, with your data preserved.', array['Clean install of Windows 11 with current updates', 'Partition and drive configuration', 'Data migration from the previous installation where recoverable', 'Recovery media for your specific configuration on request'], 'We need a valid licence for the edition being installed, or you can add one to the order.', null, false, 'published', 40),
  ('drivers', 'drivers', 'Driver and software setup', 'The right drivers from the right source, and the software you actually use, configured.', array['Chipset, graphics, network and storage drivers from vendor sources', 'Firmware and BIOS updates where they address a real issue', 'Application installation and configuration', 'Removal of preinstalled software you did not ask for'], null, null, false, 'published', 50),
  ('optimisation', 'optimisation', 'Performance optimisation', 'Measuring what the machine does now, changing the thing that is actually limiting it, then measuring again.', array['Baseline measurement before any change', 'Memory profile (XMP/EXPO) verification and correction', 'Fan curve tuning for the noise level you want', 'Storage configuration and boot time work', 'Before-and-after figures so the change is visible'], 'Results depend entirely on what was wrong to begin with. We do not promise a percentage in advance.', null, false, 'published', 60),
  ('thermal', 'thermal', 'Thermal testing', 'Sustained load testing to find out what the machine holds, not what it peaks at.', array['Extended load testing with temperature and clock logging', 'Thermal paste and cooler mounting inspection', 'Case airflow assessment and fan configuration', 'Recommendations ordered by what would actually help most'], null, null, false, 'published', 70),
  ('troubleshooting', 'troubleshooting', 'Hardware troubleshooting', 'Machines that will not boot, crash under load, or have started behaving differently.', array['No-boot and no-display diagnosis', 'Crash, freeze and blue screen investigation', 'Peripheral and connectivity faults', 'Post-repair verification before the machine goes back'], null, null, false, 'published', 80)
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  short_description = excluded.short_description,
  includes = excluded.includes,
  note = excluded.note,
  price_text = excluded.price_text,
  featured = excluded.featured,
  sort_order = excluded.sort_order,
  updated_at = now();


-- ---------------------------------------------------------------------------
-- build_presets
-- ---------------------------------------------------------------------------
insert into build_presets (
  id, slug, name, audience, tagline, rationale, highlights, items,
  status, sort_order
) values
  ('starter-1080p', 'starter-1080p', 'Ascent 1080p', 'gaming', 'A first custom build for high-refresh 1080p play.', 'Spends where frame rate comes from and nowhere else: a current six-core processor, a card with enough memory to age well, and a board on the AM5 socket so the processor can be replaced later without changing anything else.', array['AM5 platform, so a processor upgrade does not mean a new board', '16 GB of memory in two modules, leaving two slots free', 'Air cooled, which keeps the part count and the noise down'], '[{"category":"cpu","component_id":"cpu-amd-ryzen-5-7600x","quantity":1},{"category":"motherboard","component_id":"mb-asus-rog-strix-b850-f","quantity":1},{"category":"cooler","component_id":"cool-deepcool-ak620-g2","quantity":1},{"category":"ram","component_id":"ram-xpg-lancer-blade-16gb-ddr5-5600","quantity":1},{"category":"gpu","component_id":"gpu-msi-rtx-5060-ti-16g","quantity":1},{"category":"storage","component_id":"ssd-kingston-nv3-1tb","quantity":1},{"category":"psu","component_id":"psu-deepcool-pn650m","quantity":1},{"category":"case","component_id":"case-nzxt-h5-flow","quantity":1},{"category":"os","component_id":"os-windows-11-home","quantity":1}]'::jsonb, 'published', 10),
  ('gaming-1440p', 'gaming-1440p', 'Meridian 1440p', 'gaming', 'High-refresh 1440p with room to grow.', 'The configuration most gaming customers end up at. A cache-heavy gaming processor, a 16 GB card sized for 1440p, and a power supply with enough headroom that a bigger card later does not mean a second purchase.', array['32 GB of low-latency DDR5-6000 CL30', '2 TB NVMe boot drive, no secondary drive needed on day one', '850 W supply leaves headroom for a larger card later'], '[{"category":"cpu","component_id":"cpu-amd-ryzen-7-9800x3d","quantity":1},{"category":"motherboard","component_id":"mb-asus-rog-strix-b850-f","quantity":1},{"category":"cooler","component_id":"cool-arctic-liquid-freezer-iii-360","quantity":1},{"category":"ram","component_id":"ram-teamgroup-vulcan-32gb-ddr5-6000","quantity":1},{"category":"gpu","component_id":"gpu-sapphire-rx-9070-xt","quantity":1},{"category":"storage","component_id":"ssd-wd-black-sn850x-2tb","quantity":1},{"category":"psu","component_id":"psu-deepcool-pn850m","quantity":1},{"category":"case","component_id":"case-corsair-frame-4000d-rs","quantity":1},{"category":"os","component_id":"os-windows-11-home","quantity":1}]'::jsonb, 'published', 20),
  ('gaming-4k', 'gaming-4k', 'Summit 4K', 'gaming', 'Built around the fastest card the budget allows.', 'At 4K the graphics card sets the ceiling, so the rest of the build exists to keep it fed and cool: a 360 mm radiator, a case with real clearance for a 340 mm card, and a supply sized with headroom above the estimated draw.', array['Dual-chamber case with room for a long card and a 360 mm radiator', '1000 W supply against an estimated draw well under it', '6 TB of NVMe storage across two drives'], '[{"category":"cpu","component_id":"cpu-amd-ryzen-7-9800x3d","quantity":1},{"category":"motherboard","component_id":"mb-msi-mag-x870-tomahawk","quantity":1},{"category":"cooler","component_id":"cool-arctic-liquid-freezer-iii-360","quantity":1},{"category":"ram","component_id":"ram-teamgroup-vulcan-32gb-ddr5-6000","quantity":1},{"category":"gpu","component_id":"gpu-gigabyte-rtx-5080-gaming-oc","quantity":1},{"category":"storage","component_id":"ssd-wd-black-sn850x-2tb","quantity":1},{"category":"storage","component_id":"ssd-wd-black-sn7100-4tb","quantity":1},{"category":"psu","component_id":"psu-deepcool-pn1000m","quantity":1},{"category":"case","component_id":"case-lian-li-o11d-evo-rgb","quantity":1},{"category":"os","component_id":"os-windows-11-pro","quantity":1}]'::jsonb, 'published', 30),
  ('creator-workstation', 'creator-workstation', 'Studio 16C', 'workstation', 'Rendering, editing and compile jobs that scale with cores.', 'Sixteen cores and 64 GB of memory, because export and build times respond to both. Storage is split so the project drive is not competing with the operating system.', array['16-core processor for export, render and compile work', '64 GB of DDR5 with two slots still free', 'Separate operating system and project drives'], '[{"category":"cpu","component_id":"cpu-amd-ryzen-9-9950x","quantity":1},{"category":"motherboard","component_id":"mb-msi-mag-x870-tomahawk","quantity":1},{"category":"cooler","component_id":"cool-arctic-liquid-freezer-iii-360","quantity":1},{"category":"ram","component_id":"ram-teamgroup-delta-64gb-ddr5-6000","quantity":1},{"category":"gpu","component_id":"gpu-msi-rtx-5060-ti-16g","quantity":1},{"category":"storage","component_id":"ssd-wd-black-sn850x-2tb","quantity":1},{"category":"storage","component_id":"ssd-wd-black-sn7100-4tb","quantity":1},{"category":"psu","component_id":"psu-deepcool-pn1000m","quantity":1},{"category":"case","component_id":"case-corsair-frame-4000d-rs","quantity":1},{"category":"os","component_id":"os-windows-11-pro","quantity":1}]'::jsonb, 'published', 40),
  ('engineering-workstation', 'engineering-workstation', 'Atlas 24C', 'workstation', 'Large datasets, simulation and heavy virtualisation.', 'Core count and memory capacity first, on a platform with five M.2 slots so storage can be added without replacing anything. A job that fits in memory finishes; one that spills to disk takes an order of magnitude longer.', array['24 cores on the LGA1851 platform', '64 GB of DDR5, expandable to 256 GB on this board', 'Five M.2 slots on the board for future storage'], '[{"category":"cpu","component_id":"cpu-intel-core-ultra-9-285k","quantity":1},{"category":"motherboard","component_id":"mb-msi-mpg-z890-carbon","quantity":1},{"category":"cooler","component_id":"cool-arctic-liquid-freezer-iii-360","quantity":1},{"category":"ram","component_id":"ram-teamgroup-delta-64gb-ddr5-6000","quantity":1},{"category":"gpu","component_id":"gpu-sapphire-rx-9070-xt","quantity":1},{"category":"storage","component_id":"ssd-wd-black-sn850x-2tb","quantity":1},{"category":"storage","component_id":"ssd-wd-black-sn7100-4tb","quantity":1},{"category":"psu","component_id":"psu-gigabyte-ud1300gm","quantity":1},{"category":"case","component_id":"case-lian-li-o11d-evo-rgb","quantity":1},{"category":"os","component_id":"os-windows-11-pro","quantity":1}]'::jsonb, 'published', 50),
  ('compact-itx', 'compact-itx', 'Transit ITX', 'gaming', 'A mini-ITX board in a case that still takes a full-size card.', 'Small-form-factor builds are constrained by clearance before anything else. This pairs a mini-ITX board with a case that accepts it, so the board footprint shrinks without forcing compromises on the card or the cooler.', array['Mini-ITX board with Wi-Fi 7 and a PCIe 5.0 graphics slot', 'Two memory slots, so one 32 GB kit fills it', 'Card and cooler checked against the case clearance figures'], '[{"category":"cpu","component_id":"cpu-amd-ryzen-7-7800x3d","quantity":1},{"category":"motherboard","component_id":"mb-asus-rog-strix-b850-i","quantity":1},{"category":"cooler","component_id":"cool-deepcool-ak620-g2","quantity":1},{"category":"ram","component_id":"ram-teamgroup-vulcan-32gb-ddr5-6000","quantity":1},{"category":"gpu","component_id":"gpu-msi-rtx-5060-ti-16g","quantity":1},{"category":"storage","component_id":"ssd-wd-black-sn850x-1tb","quantity":1},{"category":"psu","component_id":"psu-deepcool-pn750m","quantity":1},{"category":"case","component_id":"case-nzxt-h5-flow","quantity":1},{"category":"os","component_id":"os-windows-11-home","quantity":1}]'::jsonb, 'published', 60)
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  audience = excluded.audience,
  tagline = excluded.tagline,
  rationale = excluded.rationale,
  highlights = excluded.highlights,
  items = excluded.items,
  sort_order = excluded.sort_order,
  updated_at = now();
