-- ===========================================================================
-- PC Builders Canada - development seed data
-- ===========================================================================
-- GENERATED FILE - do not edit by hand.
-- Source: src/lib/catalog/sample-catalog.ts
-- Regenerate with: npm run db:seed:generate
--
-- Every row is inserted with data_confidence = 'sample'. These part
-- specifications have NOT been verified against manufacturer documentation
-- and the prices are placeholders. Verify a row, then set its
-- data_confidence to 'verified'.
-- ===========================================================================

insert into components (
  id,
  sku,
  slug,
  category,
  brand,
  model,
  description,
  price_cents,
  cost_cents,
  stock_quantity,
  low_stock_threshold,
  image_url,
  active,
  data_confidence,
  socket,
  supported_sockets,
  chipset,
  memory_slots,
  max_memory_gb,
  m2_slots,
  sata_ports,
  form_factor,
  supported_form_factors,
  memory_type,
  memory_capacity_gb,
  memory_modules,
  memory_speed_mts,
  tdp_watts,
  recommended_psu_watts,
  psu_wattage,
  psu_efficiency,
  psu_form_factor,
  gpu_length_mm,
  max_gpu_length_mm,
  cooler_height_mm,
  max_cooler_height_mm,
  radiator_support_mm,
  radiator_size_mm,
  cooler_type,
  cooling_capacity_watts,
  storage_interface,
  storage_capacity_gb,
  pcie_version,
  specs
) values
  ('cpu-amd-ryzen-5-7600x', 'CPU-AMD-7600X', 'cpu-amd-ryzen-5-7600x', 'cpu', 'AMD', 'Ryzen 5 7600X', 'Six-core AM5 processor for 1080p and 1440p gaming builds. A sensible floor for a new system that still leaves an upgrade path on the AM5 socket.', 26900, 22058, 14, 3, null, true, 'sample', 'AM5', null, null, null, null, null, null, null, null, 'ddr5', null, null, null, 105, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"cores":6,"threads":12,"base_clock_ghz":4.7,"integrated_graphics":true}'::jsonb),
  ('cpu-amd-ryzen-7-7800x3d', 'CPU-AMD-7800X3D', 'cpu-amd-ryzen-7-7800x3d', 'cpu', 'AMD', 'Ryzen 7 7800X3D', 'Eight-core AM5 processor with stacked cache. Aimed squarely at high-framerate gaming where cache-sensitive titles benefit most.', 51900, 42558, 6, 3, null, true, 'sample', 'AM5', null, null, null, null, null, null, null, null, 'ddr5', null, null, null, 120, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"cores":8,"threads":16,"cache_note":"3D V-Cache","integrated_graphics":true}'::jsonb),
  ('cpu-amd-ryzen-7-9800x3d', 'CPU-AMD-9800X3D', 'cpu-amd-ryzen-7-9800x3d', 'cpu', 'AMD', 'Ryzen 7 9800X3D', 'Current-generation eight-core AM5 gaming processor with stacked cache. The default choice in most of our high-framerate gaming builds.', 69900, 57318, 4, 4, null, true, 'sample', 'AM5', null, null, null, null, null, null, null, null, 'ddr5', null, null, null, 120, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"cores":8,"threads":16,"cache_note":"3D V-Cache","integrated_graphics":true}'::jsonb),
  ('cpu-amd-ryzen-9-9950x', 'CPU-AMD-9950X', 'cpu-amd-ryzen-9-9950x', 'cpu', 'AMD', 'Ryzen 9 9950X', 'Sixteen-core AM5 processor for rendering, compilation and multi-track production work where core count is the bottleneck.', 84900, 69618, 5, 3, null, true, 'sample', 'AM5', null, null, null, null, null, null, null, null, 'ddr5', null, null, null, 170, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"cores":16,"threads":32,"integrated_graphics":true}'::jsonb),
  ('cpu-intel-core-ultra-5-245k', 'CPU-INT-U5245K', 'cpu-intel-core-ultra-5-245k', 'cpu', 'Intel', 'Core Ultra 5 245K', 'Mid-range LGA1851 processor for mixed gaming and productivity workloads with integrated graphics for troubleshooting without a GPU.', 38900, 31898, 9, 3, null, true, 'sample', 'LGA1851', null, null, null, null, null, null, null, null, 'ddr5', null, null, null, 125, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"cores":14,"threads":14,"integrated_graphics":true}'::jsonb),
  ('cpu-intel-core-ultra-7-265k', 'CPU-INT-U7265K', 'cpu-intel-core-ultra-7-265k', 'cpu', 'Intel', 'Core Ultra 7 265K', 'Twenty-core LGA1851 processor balancing gaming performance with heavily threaded creative work.', 54900, 45018, 7, 3, null, true, 'sample', 'LGA1851', null, null, null, null, null, null, null, null, 'ddr5', null, null, null, 125, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"cores":20,"threads":20,"integrated_graphics":true}'::jsonb),
  ('cpu-intel-core-ultra-9-285k', 'CPU-INT-U9285K', 'cpu-intel-core-ultra-9-285k', 'cpu', 'Intel', 'Core Ultra 9 285K', 'Flagship LGA1851 processor for workstation duty: simulation, rendering and large compile jobs.', 82900, 67978, 3, 3, null, true, 'sample', 'LGA1851', null, null, null, null, null, null, null, null, 'ddr5', null, null, null, 125, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"cores":24,"threads":24,"integrated_graphics":true}'::jsonb),
  ('mb-asrock-b650m-pro-rs', 'MB-ASR-B650MPRORS', 'mb-asrock-b650m-pro-rs', 'motherboard', 'ASRock', 'B650M PRO RS', 'Micro-ATX AM5 board for compact builds that still want DDR5 and two M.2 slots.', 17900, 14678, 11, 3, null, true, 'sample', 'AM5', null, 'B650', 4, 192, 2, 4, 'micro-atx', null, 'ddr5', null, null, null, 40, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 4, '{"wifi":false,"rear_usb_note":"Check manual for exact port count"}'::jsonb),
  ('mb-asus-tuf-b650-plus-wifi', 'MB-ASU-TUFB650P', 'mb-asus-tuf-b650-plus-wifi', 'motherboard', 'ASUS', 'TUF GAMING B650-PLUS WIFI', 'ATX AM5 board with solid VRM cooling and Wi-Fi. A dependable base for mid-range Ryzen gaming builds.', 27900, 22878, 8, 3, null, true, 'sample', 'AM5', null, 'B650', 4, 192, 3, 4, 'atx', null, 'ddr5', null, null, null, 45, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 4, '{"wifi":true}'::jsonb),
  ('mb-asus-rog-strix-b850-f', 'MB-ASU-B850F', 'mb-asus-rog-strix-b850-f', 'motherboard', 'ASUS', 'ROG STRIX B850-F GAMING WIFI', 'ATX AM5 board with PCIe 5.0 graphics and storage support, strong power delivery and Wi-Fi 7.', 38900, 31898, 6, 3, null, true, 'sample', 'AM5', null, 'B850', 4, 192, 4, 4, 'atx', null, 'ddr5', null, null, null, 50, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"wifi":true}'::jsonb),
  ('mb-msi-mag-x870-tomahawk', 'MB-MSI-X870TOMA', 'mb-msi-mag-x870-tomahawk', 'motherboard', 'MSI', 'MAG X870 TOMAHAWK WIFI', 'ATX AM5 board for high-core-count Ryzen builds, with heavy VRM cooling and generous USB4 connectivity.', 46900, 38458, 4, 3, null, true, 'sample', 'AM5', null, 'X870', 4, 256, 4, 4, 'atx', null, 'ddr5', null, null, null, 55, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"wifi":true}'::jsonb),
  ('mb-asus-rog-strix-b850-i', 'MB-ASU-B850I', 'mb-asus-rog-strix-b850-i', 'motherboard', 'ASUS', 'ROG STRIX B850-I GAMING WIFI', 'Mini-ITX AM5 board for small-form-factor builds. Two memory slots, dense layout, designed for compact cases.', 44900, 36818, 3, 3, null, true, 'sample', 'AM5', null, 'B850', 2, 96, 2, 2, 'mini-itx', null, 'ddr5', null, null, null, 40, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"wifi":true}'::jsonb),
  ('mb-gigabyte-b860-aorus-elite', 'MB-GIG-B860ELITE', 'mb-gigabyte-b860-aorus-elite', 'motherboard', 'Gigabyte', 'B860 AORUS ELITE WIFI7', 'ATX LGA1851 board with Wi-Fi 7 and multiple M.2 slots for mid-range Intel Core Ultra builds.', 29900, 24518, 7, 3, null, true, 'sample', 'LGA1851', null, 'B860', 4, 192, 3, 4, 'atx', null, 'ddr5', null, null, null, 45, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"wifi":true}'::jsonb),
  ('mb-msi-mpg-z890-carbon', 'MB-MSI-Z890CARBON', 'mb-msi-mpg-z890-carbon', 'motherboard', 'MSI', 'MPG Z890 CARBON WIFI', 'Enthusiast ATX LGA1851 board with heavy power delivery and Thunderbolt-class connectivity for workstation builds.', 62900, 51578, 2, 3, null, true, 'sample', 'LGA1851', null, 'Z890', 4, 256, 5, 4, 'atx', null, 'ddr5', null, null, null, 55, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, '{"wifi":true}'::jsonb),
  ('cool-thermalright-pa120-se', 'COOL-TR-PA120SE', 'cool-thermalright-pa120-se', 'cooler', 'Thermalright', 'Peerless Assassin 120 SE', 'Dual-tower air cooler that handles mid-range processors quietly at a low price. Our default air cooler for value builds.', 5900, 4838, 18, 3, null, true, 'sample', null, array['AM5', 'AM4', 'LGA1700', 'LGA1851'], null, null, null, null, null, null, null, null, null, null, null, 6, null, null, null, null, null, null, 155, null, null, null, 'air', 230, null, null, null, '{"fans":2,"fan_size_mm":120,"cooling_capacity_note":"Suited to ~150 W class CPUs"}'::jsonb),
  ('cool-noctua-nh-d15-g2', 'COOL-NOC-NHD15G2', 'cool-noctua-nh-d15-g2', 'cooler', 'Noctua', 'NH-D15 G2', 'Large dual-tower air cooler for high-power processors where liquid cooling is not wanted. Tall — check case clearance.', 19900, 16318, 5, 3, null, true, 'sample', null, array['AM5', 'LGA1700', 'LGA1851'], null, null, null, null, null, null, null, null, null, null, null, 8, null, null, null, null, null, null, 168, null, null, null, 'air', 280, null, null, null, '{"fans":2,"fan_size_mm":140}'::jsonb),
  ('cool-be-quiet-pure-rock-2', 'COOL-BQ-PUREROCK2', 'cool-be-quiet-pure-rock-2', 'cooler', 'be quiet!', 'Pure Rock 2', 'Single-tower air cooler for office and light gaming systems. Quiet, compact, easy to service.', 5500, 4510, 12, 3, null, true, 'sample', null, array['AM5', 'AM4', 'LGA1700', 'LGA1851'], null, null, null, null, null, null, null, null, null, null, null, 5, null, null, null, null, null, null, 155, null, null, null, 'air', 150, null, null, null, '{"fans":1,"fan_size_mm":120}'::jsonb),
  ('cool-arctic-liquid-freezer-iii-360', 'COOL-ARC-LF3-360', 'cool-arctic-liquid-freezer-iii-360', 'cooler', 'Arctic', 'Liquid Freezer III 360', '360 mm all-in-one liquid cooler with a VRM fan. Strong thermal headroom for high-power processors.', 14900, 12218, 9, 3, null, true, 'sample', null, array['AM5', 'AM4', 'LGA1700', 'LGA1851'], null, null, null, null, null, null, null, null, null, null, null, 12, null, null, null, null, null, null, null, null, null, array[360], 'aio', 350, null, null, null, '{"fans":3,"fan_size_mm":120,"radiator_thickness_mm":38}'::jsonb),
  ('cool-corsair-icue-h150i', 'COOL-COR-H150I', 'cool-corsair-icue-h150i', 'cooler', 'Corsair', 'iCUE H150i ELITE', '360 mm all-in-one liquid cooler with software fan control and an illuminated pump head.', 22900, 18778, 6, 3, null, true, 'sample', null, array['AM5', 'AM4', 'LGA1700', 'LGA1851'], null, null, null, null, null, null, null, null, null, null, null, 14, null, null, null, null, null, null, null, null, null, array[360], 'aio', 300, null, null, null, '{"fans":3,"fan_size_mm":120}'::jsonb),
  ('cool-nzxt-kraken-240', 'COOL-NZX-KRAKEN240', 'cool-nzxt-kraken-240', 'cooler', 'NZXT', 'Kraken 240', '240 mm all-in-one liquid cooler for compact builds and cases without 360 mm radiator support.', 16900, 13858, 7, 3, null, true, 'sample', null, array['AM5', 'AM4', 'LGA1700', 'LGA1851'], null, null, null, null, null, null, null, null, null, null, null, 11, null, null, null, null, null, null, null, null, null, array[240], 'aio', 250, null, null, null, '{"fans":2,"fan_size_mm":120}'::jsonb),
  ('ram-kingston-fury-16gb-ddr5-5600', 'RAM-KIN-16G5600', 'ram-kingston-fury-16gb-ddr5-5600', 'ram', 'Kingston', 'FURY Beast 16GB (2x8GB) DDR5-5600', 'Entry DDR5 kit for office systems and light gaming.', 8900, 7298, 20, 3, null, true, 'sample', null, null, null, null, null, null, null, null, null, 'ddr5', 16, 2, 5600, 8, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"cas_latency":"CL40","profile":"XMP 3.0"}'::jsonb),
  ('ram-corsair-vengeance-32gb-ddr5-6000', 'RAM-COR-32G6000', 'ram-corsair-vengeance-32gb-ddr5-6000', 'ram', 'Corsair', 'Vengeance 32GB (2x16GB) DDR5-6000', 'The standard memory kit in most of our gaming builds: 32 GB in two modules, leaving two slots free.', 15900, 13038, 15, 3, null, true, 'sample', null, null, null, null, null, null, null, null, null, 'ddr5', 32, 2, 6000, 10, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"cas_latency":"CL30","profile":"EXPO / XMP"}'::jsonb),
  ('ram-gskill-trident-z5-64gb-ddr5-6000', 'RAM-GSK-64G6000', 'ram-gskill-trident-z5-64gb-ddr5-6000', 'ram', 'G.Skill', 'Trident Z5 Neo 64GB (2x32GB) DDR5-6000', 'High-capacity dual-module kit for workstation duty: large project files, virtual machines, multi-app workloads.', 29900, 24518, 6, 3, null, true, 'sample', null, null, null, null, null, null, null, null, null, 'ddr5', 64, 2, 6000, 12, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"cas_latency":"CL30","profile":"EXPO"}'::jsonb),
  ('ram-crucial-pro-96gb-ddr5-5600', 'RAM-CRU-96G5600', 'ram-crucial-pro-96gb-ddr5-5600', 'ram', 'Crucial', 'Pro 96GB (2x48GB) DDR5-5600', 'Very high capacity kit for simulation, large datasets and heavy virtualisation.', 43900, 35998, 3, 3, null, true, 'sample', null, null, null, null, null, null, null, null, null, 'ddr5', 96, 2, 5600, 14, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"cas_latency":"CL46"}'::jsonb),
  ('ram-corsair-lpx-32gb-ddr4-3600', 'RAM-COR-32G3600D4', 'ram-corsair-lpx-32gb-ddr4-3600', 'ram', 'Corsair', 'Vengeance LPX 32GB (2x16GB) DDR4-3600', 'DDR4 kit kept in stock for upgrades and repairs to older AM4 and LGA1200 systems. Not compatible with DDR5 boards.', 9900, 8118, 10, 3, null, true, 'sample', null, null, null, null, null, null, null, null, null, 'ddr4', 32, 2, 3600, 8, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"cas_latency":"CL18"}'::jsonb),
  ('gpu-asus-prime-rtx-5060-ti', 'GPU-ASU-5060TI', 'gpu-asus-prime-rtx-5060-ti', 'gpu', 'ASUS', 'PRIME GeForce RTX 5060 Ti 16GB', 'Compact card for 1080p and entry 1440p gaming. Short enough for small cases.', 62900, 51578, 10, 3, null, true, 'sample', null, null, null, null, null, null, null, null, null, null, null, null, null, 180, 600, null, null, null, 242, null, null, null, null, null, null, null, null, null, 5, '{"vram_gb":16,"slots":2,"power_connectors":"1x 8-pin"}'::jsonb),
  ('gpu-msi-ventus-rtx-5070', 'GPU-MSI-5070', 'gpu-msi-ventus-rtx-5070', 'gpu', 'MSI', 'GeForce RTX 5070 VENTUS 3X 12GB', 'Mainstream 1440p card with a triple-fan cooler.', 89900, 73718, 8, 3, null, true, 'sample', null, null, null, null, null, null, null, null, null, null, null, null, null, 250, 650, null, null, null, 304, null, null, null, null, null, null, null, null, null, 5, '{"vram_gb":12,"slots":2,"power_connectors":"1x 12V-2x6"}'::jsonb),
  ('gpu-gigabyte-rtx-5070-ti', 'GPU-GIG-5070TI', 'gpu-gigabyte-rtx-5070-ti', 'gpu', 'Gigabyte', 'GeForce RTX 5070 Ti GAMING OC 16GB', 'High-refresh 1440p and entry 4K card with a large triple-fan cooler.', 124900, 102418, 5, 3, null, true, 'sample', null, null, null, null, null, null, null, null, null, null, null, null, null, 300, 750, null, null, null, 336, null, null, null, null, null, null, null, null, null, 5, '{"vram_gb":16,"slots":3,"power_connectors":"1x 12V-2x6"}'::jsonb),
  ('gpu-msi-ventus-rtx-5080', 'GPU-MSI-5080', 'gpu-msi-ventus-rtx-5080', 'gpu', 'MSI', 'GeForce RTX 5080 VENTUS 3X OC 16GB', '4K gaming card and a strong option for GPU-accelerated creative work.', 169900, 139318, 3, 3, null, true, 'sample', null, null, null, null, null, null, null, null, null, null, null, null, null, 360, 850, null, null, null, 336, null, null, null, null, null, null, null, null, null, 5, '{"vram_gb":16,"slots":3,"power_connectors":"1x 12V-2x6"}'::jsonb),
  ('gpu-gigabyte-rtx-5090', 'GPU-GIG-5090', 'gpu-gigabyte-rtx-5090', 'gpu', 'Gigabyte', 'GeForce RTX 5090 WINDFORCE 32GB', 'Flagship card for 4K high-refresh gaming and large GPU workloads. Long, heavy and power-hungry — case and PSU need to match.', 329900, 270518, 2, 2, null, true, 'sample', null, null, null, null, null, null, null, null, null, null, null, null, null, 575, 1000, null, null, null, 340, null, null, null, null, null, null, null, null, null, 5, '{"vram_gb":32,"slots":3.5,"power_connectors":"1x 12V-2x6"}'::jsonb),
  ('gpu-sapphire-rx-9070-xt', 'GPU-SAP-9070XT', 'gpu-sapphire-rx-9070-xt', 'gpu', 'Sapphire', 'PULSE Radeon RX 9070 XT 16GB', 'AMD 1440p and 4K card with 16 GB of memory and a triple-fan cooler.', 109900, 90118, 6, 3, null, true, 'sample', null, null, null, null, null, null, null, null, null, null, null, null, null, 304, 750, null, null, null, 320, null, null, null, null, null, null, null, null, null, 5, '{"vram_gb":16,"slots":2.5,"power_connectors":"2x 8-pin"}'::jsonb),
  ('ssd-wd-black-sn850x-1tb', 'SSD-WD-SN850X1T', 'ssd-wd-black-sn850x-1tb', 'storage', 'Western Digital', 'WD_BLACK SN850X 1TB NVMe', 'Fast M.2 NVMe drive. A good single-drive boot and game library option.', 12900, 10578, 22, 3, null, true, 'sample', null, null, null, null, null, null, null, null, null, null, null, null, null, 7, null, null, null, null, null, null, null, null, null, null, null, null, 'nvme-m2', 1000, 4, '{"form_factor":"M.2 2280","dram_cache":true}'::jsonb),
  ('ssd-samsung-990-pro-2tb', 'SSD-SAM-990P2T', 'ssd-samsung-990-pro-2tb', 'storage', 'Samsung', '990 PRO 2TB NVMe', 'High-performance 2 TB M.2 drive. Our default boot drive for gaming and workstation builds.', 22900, 18778, 13, 3, null, true, 'sample', null, null, null, null, null, null, null, null, null, null, null, null, null, 8, null, null, null, null, null, null, null, null, null, null, null, null, 'nvme-m2', 2000, 4, '{"form_factor":"M.2 2280","dram_cache":true}'::jsonb),
  ('ssd-crucial-p3-plus-4tb', 'SSD-CRU-P3P4T', 'ssd-crucial-p3-plus-4tb', 'storage', 'Crucial', 'P3 Plus 4TB NVMe', 'High-capacity M.2 drive for project files and large game libraries at a lower cost per terabyte.', 32900, 26978, 8, 3, null, true, 'sample', null, null, null, null, null, null, null, null, null, null, null, null, null, 7, null, null, null, null, null, null, null, null, null, null, null, null, 'nvme-m2', 4000, 4, '{"form_factor":"M.2 2280"}'::jsonb),
  ('ssd-samsung-870-evo-2tb', 'SSD-SAM-870E2T', 'ssd-samsung-870-evo-2tb', 'storage', 'Samsung', '870 EVO 2TB SATA', '2.5-inch SATA drive for secondary storage, or for upgrades to systems without a free M.2 slot.', 19900, 16318, 9, 3, null, true, 'sample', null, null, null, null, null, null, null, null, null, null, null, null, null, 3, null, null, null, null, null, null, null, null, null, null, null, null, 'sata', 2000, null, '{"form_factor":"2.5 inch"}'::jsonb),
  ('hdd-seagate-barracuda-4tb', 'HDD-SEA-BC4T', 'hdd-seagate-barracuda-4tb', 'storage', 'Seagate', 'BarraCuda 4TB 3.5" HDD', 'Mechanical drive for bulk storage and local backups where cost per terabyte matters.', 11900, 9758, 11, 3, null, true, 'sample', null, null, null, null, null, null, null, null, null, null, null, null, null, 6, null, null, null, null, null, null, null, null, null, null, null, null, 'sata', 4000, null, '{"form_factor":"3.5 inch","rpm":5400}'::jsonb),
  ('psu-msi-mag-a650bn', 'PSU-MSI-A650BN', 'psu-msi-mag-a650bn', 'psu', 'MSI', 'MAG A650BN 650W Bronze', 'Entry 650 W unit for office builds and low-power gaming systems.', 7900, 6478, 14, 3, null, true, 'sample', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 650, '80 PLUS Bronze', 'atx', null, null, null, null, null, null, null, null, null, null, null, '{"modular":"Non-modular"}'::jsonb),
  ('psu-corsair-rm750e', 'PSU-COR-RM750E', 'psu-corsair-rm750e', 'psu', 'Corsair', 'RM750e 750W Gold', 'Fully modular 750 W unit. A sensible match for mid-range gaming builds.', 13900, 11398, 12, 3, null, true, 'sample', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 750, '80 PLUS Gold', 'atx', null, null, null, null, null, null, null, null, null, null, null, '{"modular":"Fully modular","atx_version":"ATX 3.1"}'::jsonb),
  ('psu-be-quiet-pure-power-12m-850', 'PSU-BQ-PP12M850', 'psu-be-quiet-pure-power-12m-850', 'psu', 'be quiet!', 'Pure Power 12 M 850W Gold', 'Quiet, fully modular 850 W unit for builds with a higher-power graphics card.', 17900, 14678, 9, 3, null, true, 'sample', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 850, '80 PLUS Gold', 'atx', null, null, null, null, null, null, null, null, null, null, null, '{"modular":"Fully modular","atx_version":"ATX 3.0"}'::jsonb),
  ('psu-corsair-rm1000x', 'PSU-COR-RM1000X', 'psu-corsair-rm1000x', 'psu', 'Corsair', 'RM1000x 1000W Gold', 'Fully modular 1000 W unit with a native 12V-2x6 connector for current high-power graphics cards.', 25900, 21238, 7, 3, null, true, 'sample', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 1000, '80 PLUS Gold', 'atx', null, null, null, null, null, null, null, null, null, null, null, '{"modular":"Fully modular","atx_version":"ATX 3.1"}'::jsonb),
  ('psu-seasonic-prime-tx-1300', 'PSU-SEA-TX1300', 'psu-seasonic-prime-tx-1300', 'psu', 'Seasonic', 'PRIME TX-1300 1300W Titanium', 'High-capacity Titanium-rated unit for flagship graphics cards and high-core-count workstations.', 54900, 45018, 3, 3, null, true, 'sample', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 1300, '80 PLUS Titanium', 'atx', null, null, null, null, null, null, null, null, null, null, null, '{"modular":"Fully modular","atx_version":"ATX 3.0"}'::jsonb),
  ('psu-corsair-sf750', 'PSU-COR-SF750', 'psu-corsair-sf750', 'psu', 'Corsair', 'SF750 750W Platinum SFX', 'Small-form-factor 750 W unit for mini-ITX builds.', 24900, 20418, 5, 3, null, true, 'sample', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 750, '80 PLUS Platinum', 'sfx', null, null, null, null, null, null, null, null, null, null, null, '{"modular":"Fully modular"}'::jsonb),
  ('case-cooler-master-nr200p', 'CASE-CM-NR200P', 'case-cooler-master-nr200p', 'case', 'Cooler Master', 'MasterBox NR200P', 'Mini-ITX case for small builds. Takes an SFX power supply and a 240 mm radiator.', 12900, 10578, 6, 3, null, true, 'sample', null, null, null, null, null, null, null, null, array['mini-itx']::form_factor[], null, null, null, null, null, null, null, null, 'sfx', null, 330, null, 155, array[240], null, null, null, null, null, null, '{"volume_litres":18.25,"side_panel":"Steel / tempered glass options"}'::jsonb),
  ('case-nzxt-h5-flow', 'CASE-NZX-H5FLOW', 'case-nzxt-h5-flow', 'case', 'NZXT', 'H5 Flow', 'Compact ATX case with a perforated front panel and straightforward cable routing.', 12900, 10578, 10, 3, null, true, 'sample', null, null, null, null, null, null, null, null, array['atx', 'micro-atx', 'mini-itx']::form_factor[], null, null, null, null, null, null, null, null, 'atx', null, 365, null, 165, array[240, 280, 360], null, null, null, null, null, null, '{"front_panel":"Perforated steel"}'::jsonb),
  ('case-corsair-4000d-airflow', 'CASE-COR-4000DAF', 'case-corsair-4000d-airflow', 'case', 'Corsair', '4000D Airflow', 'Mid-tower with a high-airflow front panel and a clean cable channel. A dependable default for most builds.', 13900, 11398, 12, 3, null, true, 'sample', null, null, null, null, null, null, null, null, array['atx', 'micro-atx', 'mini-itx']::form_factor[], null, null, null, null, null, null, null, null, 'atx', null, 360, null, 170, array[240, 280, 360], null, null, null, null, null, null, '{"front_panel":"High-airflow steel"}'::jsonb),
  ('case-fractal-north', 'CASE-FRA-NORTH', 'case-fractal-north', 'case', 'Fractal Design', 'North', 'Mid-tower with a walnut front. Chosen when the machine sits on a desk in a room people actually use.', 18900, 15498, 7, 3, null, true, 'sample', null, null, null, null, null, null, null, null, array['atx', 'micro-atx', 'mini-itx']::form_factor[], null, null, null, null, null, null, null, null, 'atx', null, 355, null, 170, array[240, 280, 360], null, null, null, null, null, null, '{"front_panel":"Walnut slats"}'::jsonb),
  ('case-lian-li-o11d-evo', 'CASE-LL-O11DEVO', 'case-lian-li-o11d-evo', 'case', 'Lian Li', 'O11 Dynamic EVO', 'Dual-chamber showcase case with wide radiator support. The usual choice for builds meant to be looked at.', 21900, 17958, 5, 3, null, true, 'sample', null, null, null, null, null, null, null, null, array['e-atx', 'atx', 'micro-atx', 'mini-itx']::form_factor[], null, null, null, null, null, null, null, null, 'atx', null, 423, null, 167, array[240, 280, 360], null, null, null, null, null, null, '{"layout":"Dual chamber","glass":"Tempered glass front and side"}'::jsonb),
  ('case-fractal-meshify-2', 'CASE-FRA-MESH2', 'case-fractal-meshify-2', 'case', 'Fractal Design', 'Meshify 2', 'Large airflow-focused case with room for long cards, big radiators and a lot of drives. Suited to workstations.', 22900, 18778, 4, 3, null, true, 'sample', null, null, null, null, null, null, null, null, array['e-atx', 'atx', 'micro-atx', 'mini-itx']::form_factor[], null, null, null, null, null, null, null, null, 'atx', null, 460, null, 185, array[240, 280, 360, 420], null, null, null, null, null, null, '{"drive_bays":"Up to 14 with brackets"}'::jsonb),
  ('os-none', 'OS-NONE', 'os-none', 'os', 'PC Builders Canada', 'No operating system', 'Ships without an OS installed. Choose this if you are supplying your own licence or installing Linux yourself.', 0, 0, 999, 0, null, true, 'sample', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"note":"System is still tested before shipping using our own bootable media."}'::jsonb),
  ('os-windows-11-home', 'OS-MS-W11HOME', 'os-windows-11-home', 'os', 'Microsoft', 'Windows 11 Home', 'Windows 11 Home licence, installed and updated before the system ships.', 15900, 13038, 999, 10, null, true, 'sample', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"edition":"Home","delivery":"Pre-installed and activated"}'::jsonb),
  ('os-windows-11-pro', 'OS-MS-W11PRO', 'os-windows-11-pro', 'os', 'Microsoft', 'Windows 11 Pro', 'Windows 11 Pro licence. Adds BitLocker, Remote Desktop host and domain join — the usual choice for work machines.', 23900, 19598, 999, 10, null, true, 'sample', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"edition":"Pro","delivery":"Pre-installed and activated"}'::jsonb),
  ('acc-arctic-p12-5pack', 'ACC-ARC-P12X5', 'acc-arctic-p12-5pack', 'accessory', 'Arctic', 'P12 PWM PST 120mm fans (5-pack)', 'Additional case fans for builds that need more intake or exhaust.', 4900, 4018, 16, 3, null, true, 'sample', null, null, null, null, null, null, null, null, null, null, null, null, null, 8, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"size_mm":120,"quantity":5}'::jsonb),
  ('acc-sleeved-cable-kit', 'ACC-PCB-CABLEKIT', 'acc-sleeved-cable-kit', 'accessory', 'PC Builders Canada', 'Sleeved cable extension kit', 'Individually sleeved extensions for the visible 24-pin, CPU and GPU cables. Fitted during assembly.', 5900, 4838, 8, 3, null, true, 'sample', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"note":"Colour selected after order — we confirm before building."}'::jsonb),
  ('acc-thermal-paste-upgrade', 'ACC-PCB-TIMUP', 'acc-thermal-paste-upgrade', 'accessory', 'Thermal Grizzly', 'Kryonaut thermal compound application', 'Higher-grade thermal compound applied in place of the cooler default paste.', 2500, 2050, 20, 3, null, true, 'sample', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"note":"Applied during assembly"}'::jsonb),
  ('acc-recovery-usb', 'ACC-PCB-RECUSB', 'acc-recovery-usb', 'accessory', 'PC Builders Canada', 'Recovery USB drive', 'Bootable USB with the installed OS image and the drivers for your exact configuration, so a reinstall does not need another machine.', 3500, 2870, 25, 3, null, true, 'sample', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '{"capacity_gb":32}'::jsonb)
on conflict (id) do update set
  sku = excluded.sku,
  slug = excluded.slug,
  category = excluded.category,
  brand = excluded.brand,
  model = excluded.model,
  description = excluded.description,
  price_cents = excluded.price_cents,
  cost_cents = excluded.cost_cents,
  stock_quantity = excluded.stock_quantity,
  low_stock_threshold = excluded.low_stock_threshold,
  image_url = excluded.image_url,
  active = excluded.active,
  data_confidence = excluded.data_confidence,
  socket = excluded.socket,
  supported_sockets = excluded.supported_sockets,
  chipset = excluded.chipset,
  memory_slots = excluded.memory_slots,
  max_memory_gb = excluded.max_memory_gb,
  m2_slots = excluded.m2_slots,
  sata_ports = excluded.sata_ports,
  form_factor = excluded.form_factor,
  supported_form_factors = excluded.supported_form_factors,
  memory_type = excluded.memory_type,
  memory_capacity_gb = excluded.memory_capacity_gb,
  memory_modules = excluded.memory_modules,
  memory_speed_mts = excluded.memory_speed_mts,
  tdp_watts = excluded.tdp_watts,
  recommended_psu_watts = excluded.recommended_psu_watts,
  psu_wattage = excluded.psu_wattage,
  psu_efficiency = excluded.psu_efficiency,
  psu_form_factor = excluded.psu_form_factor,
  gpu_length_mm = excluded.gpu_length_mm,
  max_gpu_length_mm = excluded.max_gpu_length_mm,
  cooler_height_mm = excluded.cooler_height_mm,
  max_cooler_height_mm = excluded.max_cooler_height_mm,
  radiator_support_mm = excluded.radiator_support_mm,
  radiator_size_mm = excluded.radiator_size_mm,
  cooler_type = excluded.cooler_type,
  cooling_capacity_watts = excluded.cooling_capacity_watts,
  storage_interface = excluded.storage_interface,
  storage_capacity_gb = excluded.storage_capacity_gb,
  pcie_version = excluded.pcie_version,
  specs = excluded.specs,
  updated_at = now();
