import type { ComponentRecord } from '@/lib/catalog/types';

/**
 * DEVELOPMENT / SAMPLE CATALOGUE
 * ------------------------------
 * Every row here is marked `data_confidence: 'sample'`. The part names are
 * real retail products, but the specifications and prices in this file have
 * NOT been checked against manufacturer documentation or current Canadian
 * retail pricing. They exist so the configurator, compatibility engine and
 * pricing engine have something realistic to operate on during development.
 *
 * Before this catalogue is used to sell anything:
 *   1. Replace each row's specs with values read off the manufacturer's
 *      spec sheet (socket, dimensions, wattage, slot counts).
 *   2. Replace prices with real landed cost + margin.
 *   3. Flip `data_confidence` to 'verified' per row as it is checked.
 * The UI shows an "unverified spec" marker for every row still set to
 * 'sample', so nothing on this site claims to be a confirmed figure.
 *
 * Component ids are readable slugs rather than UUIDs on purpose: saved builds
 * and order snapshots store these ids as JSON, and a human-readable id makes
 * support tickets and database inspection far easier. See docs/database.md.
 */

type ComponentSeed = Partial<ComponentRecord> &
  Pick<
    ComponentRecord,
    'id' | 'sku' | 'category' | 'brand' | 'model' | 'description' | 'price_cents'
  >;

const NOW = '2026-01-01T00:00:00.000Z';

function component(seed: ComponentSeed): ComponentRecord {
  return {
    slug: seed.id,
    cost_cents: Math.round(seed.price_cents * 0.82),
    stock_quantity: 8,
    low_stock_threshold: 3,
    image_url: null,
    active: true,
    data_confidence: 'sample',
    socket: null,
    supported_sockets: null,
    chipset: null,
    memory_slots: null,
    max_memory_gb: null,
    m2_slots: null,
    sata_ports: null,
    form_factor: null,
    supported_form_factors: null,
    memory_type: null,
    memory_capacity_gb: null,
    memory_modules: null,
    memory_speed_mts: null,
    tdp_watts: null,
    recommended_psu_watts: null,
    psu_wattage: null,
    psu_efficiency: null,
    psu_form_factor: null,
    gpu_length_mm: null,
    max_gpu_length_mm: null,
    cooler_height_mm: null,
    max_cooler_height_mm: null,
    radiator_support_mm: null,
    radiator_size_mm: null,
    cooler_type: null,
    cooling_capacity_watts: null,
    storage_interface: null,
    storage_capacity_gb: null,
    pcie_version: null,
    specs: {},
    created_at: NOW,
    updated_at: NOW,
    ...seed,
  } as ComponentRecord;
}

export const SAMPLE_COMPONENTS: ComponentRecord[] = [
  // -------------------------------------------------------------------------
  // Processors
  // -------------------------------------------------------------------------
  component({
    id: 'cpu-amd-ryzen-5-7600x',
    sku: 'CPU-AMD-7600X',
    category: 'cpu',
    brand: 'AMD',
    model: 'Ryzen 5 7600X',
    description:
      'Six-core AM5 processor for 1080p and 1440p gaming builds. A sensible floor for a new system that still leaves an upgrade path on the AM5 socket.',
    price_cents: 26900,
    socket: 'AM5',
    memory_type: 'ddr5',
    tdp_watts: 105,
    pcie_version: 5,
    stock_quantity: 14,
    specs: { cores: 6, threads: 12, base_clock_ghz: 4.7, integrated_graphics: true },
  }),
  component({
    id: 'cpu-amd-ryzen-7-7800x3d',
    sku: 'CPU-AMD-7800X3D',
    category: 'cpu',
    brand: 'AMD',
    model: 'Ryzen 7 7800X3D',
    description:
      'Eight-core AM5 processor with stacked cache. Aimed squarely at high-framerate gaming where cache-sensitive titles benefit most.',
    price_cents: 51900,
    socket: 'AM5',
    memory_type: 'ddr5',
    tdp_watts: 120,
    pcie_version: 5,
    stock_quantity: 6,
    specs: { cores: 8, threads: 16, cache_note: '3D V-Cache', integrated_graphics: true },
  }),
  component({
    id: 'cpu-amd-ryzen-7-9800x3d',
    sku: 'CPU-AMD-9800X3D',
    category: 'cpu',
    brand: 'AMD',
    model: 'Ryzen 7 9800X3D',
    description:
      'Current-generation eight-core AM5 gaming processor with stacked cache. The default choice in most of our high-framerate gaming builds.',
    price_cents: 69900,
    socket: 'AM5',
    memory_type: 'ddr5',
    tdp_watts: 120,
    pcie_version: 5,
    stock_quantity: 4,
    low_stock_threshold: 4,
    specs: { cores: 8, threads: 16, cache_note: '3D V-Cache', integrated_graphics: true },
  }),
  component({
    id: 'cpu-amd-ryzen-9-9950x',
    sku: 'CPU-AMD-9950X',
    category: 'cpu',
    brand: 'AMD',
    model: 'Ryzen 9 9950X',
    description:
      'Sixteen-core AM5 processor for rendering, compilation and multi-track production work where core count is the bottleneck.',
    price_cents: 84900,
    socket: 'AM5',
    memory_type: 'ddr5',
    tdp_watts: 170,
    pcie_version: 5,
    stock_quantity: 5,
    specs: { cores: 16, threads: 32, integrated_graphics: true },
  }),
  component({
    id: 'cpu-intel-core-ultra-5-245k',
    sku: 'CPU-INT-U5245K',
    category: 'cpu',
    brand: 'Intel',
    model: 'Core Ultra 5 245K',
    description:
      'Mid-range LGA1851 processor for mixed gaming and productivity workloads with integrated graphics for troubleshooting without a GPU.',
    price_cents: 38900,
    socket: 'LGA1851',
    memory_type: 'ddr5',
    tdp_watts: 125,
    pcie_version: 5,
    stock_quantity: 9,
    specs: { cores: 14, threads: 14, integrated_graphics: true },
  }),
  component({
    id: 'cpu-intel-core-ultra-7-265k',
    sku: 'CPU-INT-U7265K',
    category: 'cpu',
    brand: 'Intel',
    model: 'Core Ultra 7 265K',
    description:
      'Twenty-core LGA1851 processor balancing gaming performance with heavily threaded creative work.',
    price_cents: 54900,
    socket: 'LGA1851',
    memory_type: 'ddr5',
    tdp_watts: 125,
    pcie_version: 5,
    stock_quantity: 7,
    specs: { cores: 20, threads: 20, integrated_graphics: true },
  }),
  component({
    id: 'cpu-intel-core-ultra-9-285k',
    sku: 'CPU-INT-U9285K',
    category: 'cpu',
    brand: 'Intel',
    model: 'Core Ultra 9 285K',
    description:
      'Flagship LGA1851 processor for workstation duty: simulation, rendering and large compile jobs.',
    price_cents: 82900,
    socket: 'LGA1851',
    memory_type: 'ddr5',
    tdp_watts: 125,
    pcie_version: 5,
    stock_quantity: 3,
    specs: { cores: 24, threads: 24, integrated_graphics: true },
  }),

  // -------------------------------------------------------------------------
  // Motherboards
  // -------------------------------------------------------------------------
  component({
    id: 'mb-asrock-b650m-pro-rs',
    sku: 'MB-ASR-B650MPRORS',
    category: 'motherboard',
    brand: 'ASRock',
    model: 'B650M PRO RS',
    description:
      'Micro-ATX AM5 board for compact builds that still want DDR5 and two M.2 slots.',
    price_cents: 17900,
    socket: 'AM5',
    chipset: 'B650',
    form_factor: 'micro-atx',
    memory_type: 'ddr5',
    memory_slots: 4,
    max_memory_gb: 192,
    m2_slots: 2,
    sata_ports: 4,
    pcie_version: 4,
    tdp_watts: 40,
    stock_quantity: 11,
    specs: { wifi: false, rear_usb_note: 'Check manual for exact port count' },
  }),
  component({
    id: 'mb-asus-tuf-b650-plus-wifi',
    sku: 'MB-ASU-TUFB650P',
    category: 'motherboard',
    brand: 'ASUS',
    model: 'TUF GAMING B650-PLUS WIFI',
    description:
      'ATX AM5 board with solid VRM cooling and Wi-Fi. A dependable base for mid-range Ryzen gaming builds.',
    price_cents: 27900,
    socket: 'AM5',
    chipset: 'B650',
    form_factor: 'atx',
    memory_type: 'ddr5',
    memory_slots: 4,
    max_memory_gb: 192,
    m2_slots: 3,
    sata_ports: 4,
    pcie_version: 4,
    tdp_watts: 45,
    stock_quantity: 8,
    specs: { wifi: true },
  }),
  component({
    id: 'mb-asus-rog-strix-b850-f',
    sku: 'MB-ASU-B850F',
    category: 'motherboard',
    brand: 'ASUS',
    model: 'ROG STRIX B850-F GAMING WIFI',
    description:
      'ATX AM5 board with PCIe 5.0 graphics and storage support, strong power delivery and Wi-Fi 7.',
    price_cents: 38900,
    socket: 'AM5',
    chipset: 'B850',
    form_factor: 'atx',
    memory_type: 'ddr5',
    memory_slots: 4,
    max_memory_gb: 192,
    m2_slots: 4,
    sata_ports: 4,
    pcie_version: 5,
    tdp_watts: 50,
    stock_quantity: 6,
    specs: { wifi: true },
  }),
  component({
    id: 'mb-msi-mag-x870-tomahawk',
    sku: 'MB-MSI-X870TOMA',
    category: 'motherboard',
    brand: 'MSI',
    model: 'MAG X870 TOMAHAWK WIFI',
    description:
      'ATX AM5 board for high-core-count Ryzen builds, with heavy VRM cooling and generous USB4 connectivity.',
    price_cents: 46900,
    socket: 'AM5',
    chipset: 'X870',
    form_factor: 'atx',
    memory_type: 'ddr5',
    memory_slots: 4,
    max_memory_gb: 256,
    m2_slots: 4,
    sata_ports: 4,
    pcie_version: 5,
    tdp_watts: 55,
    stock_quantity: 4,
    specs: { wifi: true },
  }),
  component({
    id: 'mb-asus-rog-strix-b850-i',
    sku: 'MB-ASU-B850I',
    category: 'motherboard',
    brand: 'ASUS',
    model: 'ROG STRIX B850-I GAMING WIFI',
    description:
      'Mini-ITX AM5 board for small-form-factor builds. Two memory slots, dense layout, designed for compact cases.',
    price_cents: 44900,
    socket: 'AM5',
    chipset: 'B850',
    form_factor: 'mini-itx',
    memory_type: 'ddr5',
    memory_slots: 2,
    max_memory_gb: 96,
    m2_slots: 2,
    sata_ports: 2,
    pcie_version: 5,
    tdp_watts: 40,
    stock_quantity: 3,
    specs: { wifi: true },
  }),
  component({
    id: 'mb-gigabyte-b860-aorus-elite',
    sku: 'MB-GIG-B860ELITE',
    category: 'motherboard',
    brand: 'Gigabyte',
    model: 'B860 AORUS ELITE WIFI7',
    description:
      'ATX LGA1851 board with Wi-Fi 7 and multiple M.2 slots for mid-range Intel Core Ultra builds.',
    price_cents: 29900,
    socket: 'LGA1851',
    chipset: 'B860',
    form_factor: 'atx',
    memory_type: 'ddr5',
    memory_slots: 4,
    max_memory_gb: 192,
    m2_slots: 3,
    sata_ports: 4,
    pcie_version: 5,
    tdp_watts: 45,
    stock_quantity: 7,
    specs: { wifi: true },
  }),
  component({
    id: 'mb-msi-mpg-z890-carbon',
    sku: 'MB-MSI-Z890CARBON',
    category: 'motherboard',
    brand: 'MSI',
    model: 'MPG Z890 CARBON WIFI',
    description:
      'Enthusiast ATX LGA1851 board with heavy power delivery and Thunderbolt-class connectivity for workstation builds.',
    price_cents: 62900,
    socket: 'LGA1851',
    chipset: 'Z890',
    form_factor: 'atx',
    memory_type: 'ddr5',
    memory_slots: 4,
    max_memory_gb: 256,
    m2_slots: 5,
    sata_ports: 4,
    pcie_version: 5,
    tdp_watts: 55,
    stock_quantity: 2,
    specs: { wifi: true },
  }),

  // -------------------------------------------------------------------------
  // CPU coolers
  // -------------------------------------------------------------------------
  component({
    id: 'cool-thermalright-pa120-se',
    sku: 'COOL-TR-PA120SE',
    category: 'cooler',
    brand: 'Thermalright',
    model: 'Peerless Assassin 120 SE',
    description:
      'Dual-tower air cooler that handles mid-range processors quietly at a low price. Our default air cooler for value builds.',
    price_cents: 5900,
    cooler_type: 'air',
    cooler_height_mm: 155,
    supported_sockets: ['AM5', 'AM4', 'LGA1700', 'LGA1851'],
    // tdp_watts on a cooler is the power its own fans draw, not its capacity.
    tdp_watts: 6,
    cooling_capacity_watts: 230,
    stock_quantity: 18,
    specs: { fans: 2, fan_size_mm: 120, cooling_capacity_note: 'Suited to ~150 W class CPUs' },
  }),
  component({
    id: 'cool-noctua-nh-d15-g2',
    sku: 'COOL-NOC-NHD15G2',
    category: 'cooler',
    brand: 'Noctua',
    model: 'NH-D15 G2',
    description:
      'Large dual-tower air cooler for high-power processors where liquid cooling is not wanted. Tall — check case clearance.',
    price_cents: 19900,
    cooler_type: 'air',
    cooler_height_mm: 168,
    supported_sockets: ['AM5', 'LGA1700', 'LGA1851'],
    tdp_watts: 8,
    cooling_capacity_watts: 280,
    stock_quantity: 5,
    specs: { fans: 2, fan_size_mm: 140 },
  }),
  component({
    id: 'cool-be-quiet-pure-rock-2',
    sku: 'COOL-BQ-PUREROCK2',
    category: 'cooler',
    brand: 'be quiet!',
    model: 'Pure Rock 2',
    description:
      'Single-tower air cooler for office and light gaming systems. Quiet, compact, easy to service.',
    price_cents: 5500,
    cooler_type: 'air',
    cooler_height_mm: 155,
    supported_sockets: ['AM5', 'AM4', 'LGA1700', 'LGA1851'],
    tdp_watts: 5,
    cooling_capacity_watts: 150,
    stock_quantity: 12,
    specs: { fans: 1, fan_size_mm: 120 },
  }),
  component({
    id: 'cool-arctic-liquid-freezer-iii-360',
    sku: 'COOL-ARC-LF3-360',
    category: 'cooler',
    brand: 'Arctic',
    model: 'Liquid Freezer III 360',
    description:
      '360 mm all-in-one liquid cooler with a VRM fan. Strong thermal headroom for high-power processors.',
    price_cents: 14900,
    cooler_type: 'aio',
    radiator_size_mm: [360],
    supported_sockets: ['AM5', 'AM4', 'LGA1700', 'LGA1851'],
    tdp_watts: 12,
    cooling_capacity_watts: 350,
    stock_quantity: 9,
    specs: { fans: 3, fan_size_mm: 120, radiator_thickness_mm: 38 },
  }),
  component({
    id: 'cool-corsair-icue-h150i',
    sku: 'COOL-COR-H150I',
    category: 'cooler',
    brand: 'Corsair',
    model: 'iCUE H150i ELITE',
    description:
      '360 mm all-in-one liquid cooler with software fan control and an illuminated pump head.',
    price_cents: 22900,
    cooler_type: 'aio',
    radiator_size_mm: [360],
    supported_sockets: ['AM5', 'AM4', 'LGA1700', 'LGA1851'],
    tdp_watts: 14,
    cooling_capacity_watts: 300,
    stock_quantity: 6,
    specs: { fans: 3, fan_size_mm: 120 },
  }),
  component({
    id: 'cool-nzxt-kraken-240',
    sku: 'COOL-NZX-KRAKEN240',
    category: 'cooler',
    brand: 'NZXT',
    model: 'Kraken 240',
    description:
      '240 mm all-in-one liquid cooler for compact builds and cases without 360 mm radiator support.',
    price_cents: 16900,
    cooler_type: 'aio',
    radiator_size_mm: [240],
    supported_sockets: ['AM5', 'AM4', 'LGA1700', 'LGA1851'],
    tdp_watts: 11,
    cooling_capacity_watts: 250,
    stock_quantity: 7,
    specs: { fans: 2, fan_size_mm: 120 },
  }),

  // -------------------------------------------------------------------------
  // Memory
  // -------------------------------------------------------------------------
  component({
    id: 'ram-kingston-fury-16gb-ddr5-5600',
    sku: 'RAM-KIN-16G5600',
    category: 'ram',
    brand: 'Kingston',
    model: 'FURY Beast 16GB (2x8GB) DDR5-5600',
    description: 'Entry DDR5 kit for office systems and light gaming.',
    price_cents: 8900,
    memory_type: 'ddr5',
    memory_capacity_gb: 16,
    memory_modules: 2,
    memory_speed_mts: 5600,
    tdp_watts: 8,
    stock_quantity: 20,
    specs: { cas_latency: 'CL40', profile: 'XMP 3.0' },
  }),
  component({
    id: 'ram-corsair-vengeance-32gb-ddr5-6000',
    sku: 'RAM-COR-32G6000',
    category: 'ram',
    brand: 'Corsair',
    model: 'Vengeance 32GB (2x16GB) DDR5-6000',
    description:
      'The standard memory kit in most of our gaming builds: 32 GB in two modules, leaving two slots free.',
    price_cents: 15900,
    memory_type: 'ddr5',
    memory_capacity_gb: 32,
    memory_modules: 2,
    memory_speed_mts: 6000,
    tdp_watts: 10,
    stock_quantity: 15,
    specs: { cas_latency: 'CL30', profile: 'EXPO / XMP' },
  }),
  component({
    id: 'ram-gskill-trident-z5-64gb-ddr5-6000',
    sku: 'RAM-GSK-64G6000',
    category: 'ram',
    brand: 'G.Skill',
    model: 'Trident Z5 Neo 64GB (2x32GB) DDR5-6000',
    description:
      'High-capacity dual-module kit for workstation duty: large project files, virtual machines, multi-app workloads.',
    price_cents: 29900,
    memory_type: 'ddr5',
    memory_capacity_gb: 64,
    memory_modules: 2,
    memory_speed_mts: 6000,
    tdp_watts: 12,
    stock_quantity: 6,
    specs: { cas_latency: 'CL30', profile: 'EXPO' },
  }),
  component({
    id: 'ram-crucial-pro-96gb-ddr5-5600',
    sku: 'RAM-CRU-96G5600',
    category: 'ram',
    brand: 'Crucial',
    model: 'Pro 96GB (2x48GB) DDR5-5600',
    description:
      'Very high capacity kit for simulation, large datasets and heavy virtualisation.',
    price_cents: 43900,
    memory_type: 'ddr5',
    memory_capacity_gb: 96,
    memory_modules: 2,
    memory_speed_mts: 5600,
    tdp_watts: 14,
    stock_quantity: 3,
    specs: { cas_latency: 'CL46' },
  }),
  component({
    id: 'ram-corsair-lpx-32gb-ddr4-3600',
    sku: 'RAM-COR-32G3600D4',
    category: 'ram',
    brand: 'Corsair',
    model: 'Vengeance LPX 32GB (2x16GB) DDR4-3600',
    description:
      'DDR4 kit kept in stock for upgrades and repairs to older AM4 and LGA1200 systems. Not compatible with DDR5 boards.',
    price_cents: 9900,
    memory_type: 'ddr4',
    memory_capacity_gb: 32,
    memory_modules: 2,
    memory_speed_mts: 3600,
    tdp_watts: 8,
    stock_quantity: 10,
    specs: { cas_latency: 'CL18' },
  }),

  // -------------------------------------------------------------------------
  // Graphics cards
  // -------------------------------------------------------------------------
  component({
    id: 'gpu-asus-prime-rtx-5060-ti',
    sku: 'GPU-ASU-5060TI',
    category: 'gpu',
    brand: 'ASUS',
    model: 'PRIME GeForce RTX 5060 Ti 16GB',
    description:
      'Compact card for 1080p and entry 1440p gaming. Short enough for small cases.',
    price_cents: 62900,
    gpu_length_mm: 242,
    tdp_watts: 180,
    recommended_psu_watts: 600,
    pcie_version: 5,
    stock_quantity: 10,
    specs: { vram_gb: 16, slots: 2, power_connectors: '1x 8-pin' },
  }),
  component({
    id: 'gpu-msi-ventus-rtx-5070',
    sku: 'GPU-MSI-5070',
    category: 'gpu',
    brand: 'MSI',
    model: 'GeForce RTX 5070 VENTUS 3X 12GB',
    description: 'Mainstream 1440p card with a triple-fan cooler.',
    price_cents: 89900,
    gpu_length_mm: 304,
    tdp_watts: 250,
    recommended_psu_watts: 650,
    pcie_version: 5,
    stock_quantity: 8,
    specs: { vram_gb: 12, slots: 2, power_connectors: '1x 12V-2x6' },
  }),
  component({
    id: 'gpu-gigabyte-rtx-5070-ti',
    sku: 'GPU-GIG-5070TI',
    category: 'gpu',
    brand: 'Gigabyte',
    model: 'GeForce RTX 5070 Ti GAMING OC 16GB',
    description: 'High-refresh 1440p and entry 4K card with a large triple-fan cooler.',
    price_cents: 124900,
    gpu_length_mm: 336,
    tdp_watts: 300,
    recommended_psu_watts: 750,
    pcie_version: 5,
    stock_quantity: 5,
    specs: { vram_gb: 16, slots: 3, power_connectors: '1x 12V-2x6' },
  }),
  component({
    id: 'gpu-msi-ventus-rtx-5080',
    sku: 'GPU-MSI-5080',
    category: 'gpu',
    brand: 'MSI',
    model: 'GeForce RTX 5080 VENTUS 3X OC 16GB',
    description: '4K gaming card and a strong option for GPU-accelerated creative work.',
    price_cents: 169900,
    gpu_length_mm: 336,
    tdp_watts: 360,
    recommended_psu_watts: 850,
    pcie_version: 5,
    stock_quantity: 3,
    low_stock_threshold: 3,
    specs: { vram_gb: 16, slots: 3, power_connectors: '1x 12V-2x6' },
  }),
  component({
    id: 'gpu-gigabyte-rtx-5090',
    sku: 'GPU-GIG-5090',
    category: 'gpu',
    brand: 'Gigabyte',
    model: 'GeForce RTX 5090 WINDFORCE 32GB',
    description:
      'Flagship card for 4K high-refresh gaming and large GPU workloads. Long, heavy and power-hungry — case and PSU need to match.',
    price_cents: 329900,
    gpu_length_mm: 340,
    tdp_watts: 575,
    recommended_psu_watts: 1000,
    pcie_version: 5,
    stock_quantity: 2,
    low_stock_threshold: 2,
    specs: { vram_gb: 32, slots: 3.5, power_connectors: '1x 12V-2x6' },
  }),
  component({
    id: 'gpu-sapphire-rx-9070-xt',
    sku: 'GPU-SAP-9070XT',
    category: 'gpu',
    brand: 'Sapphire',
    model: 'PULSE Radeon RX 9070 XT 16GB',
    description: 'AMD 1440p and 4K card with 16 GB of memory and a triple-fan cooler.',
    price_cents: 109900,
    gpu_length_mm: 320,
    tdp_watts: 304,
    recommended_psu_watts: 750,
    pcie_version: 5,
    stock_quantity: 6,
    specs: { vram_gb: 16, slots: 2.5, power_connectors: '2x 8-pin' },
  }),

  // -------------------------------------------------------------------------
  // Storage
  // -------------------------------------------------------------------------
  component({
    id: 'ssd-wd-black-sn850x-1tb',
    sku: 'SSD-WD-SN850X1T',
    category: 'storage',
    brand: 'Western Digital',
    model: 'WD_BLACK SN850X 1TB NVMe',
    description: 'Fast M.2 NVMe drive. A good single-drive boot and game library option.',
    price_cents: 12900,
    storage_interface: 'nvme-m2',
    storage_capacity_gb: 1000,
    tdp_watts: 7,
    pcie_version: 4,
    stock_quantity: 22,
    specs: { form_factor: 'M.2 2280', dram_cache: true },
  }),
  component({
    id: 'ssd-samsung-990-pro-2tb',
    sku: 'SSD-SAM-990P2T',
    category: 'storage',
    brand: 'Samsung',
    model: '990 PRO 2TB NVMe',
    description:
      'High-performance 2 TB M.2 drive. Our default boot drive for gaming and workstation builds.',
    price_cents: 22900,
    storage_interface: 'nvme-m2',
    storage_capacity_gb: 2000,
    tdp_watts: 8,
    pcie_version: 4,
    stock_quantity: 13,
    specs: { form_factor: 'M.2 2280', dram_cache: true },
  }),
  component({
    id: 'ssd-crucial-p3-plus-4tb',
    sku: 'SSD-CRU-P3P4T',
    category: 'storage',
    brand: 'Crucial',
    model: 'P3 Plus 4TB NVMe',
    description:
      'High-capacity M.2 drive for project files and large game libraries at a lower cost per terabyte.',
    price_cents: 32900,
    storage_interface: 'nvme-m2',
    storage_capacity_gb: 4000,
    tdp_watts: 7,
    pcie_version: 4,
    stock_quantity: 8,
    specs: { form_factor: 'M.2 2280' },
  }),
  component({
    id: 'ssd-samsung-870-evo-2tb',
    sku: 'SSD-SAM-870E2T',
    category: 'storage',
    brand: 'Samsung',
    model: '870 EVO 2TB SATA',
    description:
      '2.5-inch SATA drive for secondary storage, or for upgrades to systems without a free M.2 slot.',
    price_cents: 19900,
    storage_interface: 'sata',
    storage_capacity_gb: 2000,
    tdp_watts: 3,
    stock_quantity: 9,
    specs: { form_factor: '2.5 inch' },
  }),
  component({
    id: 'hdd-seagate-barracuda-4tb',
    sku: 'HDD-SEA-BC4T',
    category: 'storage',
    brand: 'Seagate',
    model: 'BarraCuda 4TB 3.5" HDD',
    description: 'Mechanical drive for bulk storage and local backups where cost per terabyte matters.',
    price_cents: 11900,
    storage_interface: 'sata',
    storage_capacity_gb: 4000,
    tdp_watts: 6,
    stock_quantity: 11,
    specs: { form_factor: '3.5 inch', rpm: 5400 },
  }),

  // -------------------------------------------------------------------------
  // Power supplies
  // -------------------------------------------------------------------------
  component({
    id: 'psu-msi-mag-a650bn',
    sku: 'PSU-MSI-A650BN',
    category: 'psu',
    brand: 'MSI',
    model: 'MAG A650BN 650W Bronze',
    description: 'Entry 650 W unit for office builds and low-power gaming systems.',
    price_cents: 7900,
    psu_wattage: 650,
    psu_efficiency: '80 PLUS Bronze',
    psu_form_factor: 'atx',
    stock_quantity: 14,
    specs: { modular: 'Non-modular' },
  }),
  component({
    id: 'psu-corsair-rm750e',
    sku: 'PSU-COR-RM750E',
    category: 'psu',
    brand: 'Corsair',
    model: 'RM750e 750W Gold',
    description: 'Fully modular 750 W unit. A sensible match for mid-range gaming builds.',
    price_cents: 13900,
    psu_wattage: 750,
    psu_efficiency: '80 PLUS Gold',
    psu_form_factor: 'atx',
    stock_quantity: 12,
    specs: { modular: 'Fully modular', atx_version: 'ATX 3.1' },
  }),
  component({
    id: 'psu-be-quiet-pure-power-12m-850',
    sku: 'PSU-BQ-PP12M850',
    category: 'psu',
    brand: 'be quiet!',
    model: 'Pure Power 12 M 850W Gold',
    description: 'Quiet, fully modular 850 W unit for builds with a higher-power graphics card.',
    price_cents: 17900,
    psu_wattage: 850,
    psu_efficiency: '80 PLUS Gold',
    psu_form_factor: 'atx',
    stock_quantity: 9,
    specs: { modular: 'Fully modular', atx_version: 'ATX 3.0' },
  }),
  component({
    id: 'psu-corsair-rm1000x',
    sku: 'PSU-COR-RM1000X',
    category: 'psu',
    brand: 'Corsair',
    model: 'RM1000x 1000W Gold',
    description:
      'Fully modular 1000 W unit with a native 12V-2x6 connector for current high-power graphics cards.',
    price_cents: 25900,
    psu_wattage: 1000,
    psu_efficiency: '80 PLUS Gold',
    psu_form_factor: 'atx',
    stock_quantity: 7,
    specs: { modular: 'Fully modular', atx_version: 'ATX 3.1' },
  }),
  component({
    id: 'psu-seasonic-prime-tx-1300',
    sku: 'PSU-SEA-TX1300',
    category: 'psu',
    brand: 'Seasonic',
    model: 'PRIME TX-1300 1300W Titanium',
    description:
      'High-capacity Titanium-rated unit for flagship graphics cards and high-core-count workstations.',
    price_cents: 54900,
    psu_wattage: 1300,
    psu_efficiency: '80 PLUS Titanium',
    psu_form_factor: 'atx',
    stock_quantity: 3,
    specs: { modular: 'Fully modular', atx_version: 'ATX 3.0' },
  }),
  component({
    id: 'psu-corsair-sf750',
    sku: 'PSU-COR-SF750',
    category: 'psu',
    brand: 'Corsair',
    model: 'SF750 750W Platinum SFX',
    description: 'Small-form-factor 750 W unit for mini-ITX builds.',
    price_cents: 24900,
    psu_wattage: 750,
    psu_efficiency: '80 PLUS Platinum',
    psu_form_factor: 'sfx',
    stock_quantity: 5,
    specs: { modular: 'Fully modular' },
  }),

  // -------------------------------------------------------------------------
  // Cases
  // -------------------------------------------------------------------------
  component({
    id: 'case-cooler-master-nr200p',
    sku: 'CASE-CM-NR200P',
    category: 'case',
    brand: 'Cooler Master',
    model: 'MasterBox NR200P',
    description:
      'Mini-ITX case for small builds. Takes an SFX power supply and a 240 mm radiator.',
    price_cents: 12900,
    supported_form_factors: ['mini-itx'],
    max_gpu_length_mm: 330,
    max_cooler_height_mm: 155,
    radiator_support_mm: [240],
    psu_form_factor: 'sfx',
    stock_quantity: 6,
    specs: { volume_litres: 18.25, side_panel: 'Steel / tempered glass options' },
  }),
  component({
    id: 'case-nzxt-h5-flow',
    sku: 'CASE-NZX-H5FLOW',
    category: 'case',
    brand: 'NZXT',
    model: 'H5 Flow',
    description: 'Compact ATX case with a perforated front panel and straightforward cable routing.',
    price_cents: 12900,
    supported_form_factors: ['atx', 'micro-atx', 'mini-itx'],
    max_gpu_length_mm: 365,
    max_cooler_height_mm: 165,
    radiator_support_mm: [240, 280, 360],
    psu_form_factor: 'atx',
    stock_quantity: 10,
    specs: { front_panel: 'Perforated steel' },
  }),
  component({
    id: 'case-corsair-4000d-airflow',
    sku: 'CASE-COR-4000DAF',
    category: 'case',
    brand: 'Corsair',
    model: '4000D Airflow',
    description:
      'Mid-tower with a high-airflow front panel and a clean cable channel. A dependable default for most builds.',
    price_cents: 13900,
    supported_form_factors: ['atx', 'micro-atx', 'mini-itx'],
    max_gpu_length_mm: 360,
    max_cooler_height_mm: 170,
    radiator_support_mm: [240, 280, 360],
    psu_form_factor: 'atx',
    stock_quantity: 12,
    specs: { front_panel: 'High-airflow steel' },
  }),
  component({
    id: 'case-fractal-north',
    sku: 'CASE-FRA-NORTH',
    category: 'case',
    brand: 'Fractal Design',
    model: 'North',
    description:
      'Mid-tower with a walnut front. Chosen when the machine sits on a desk in a room people actually use.',
    price_cents: 18900,
    supported_form_factors: ['atx', 'micro-atx', 'mini-itx'],
    max_gpu_length_mm: 355,
    max_cooler_height_mm: 170,
    radiator_support_mm: [240, 280, 360],
    psu_form_factor: 'atx',
    stock_quantity: 7,
    specs: { front_panel: 'Walnut slats' },
  }),
  component({
    id: 'case-lian-li-o11d-evo',
    sku: 'CASE-LL-O11DEVO',
    category: 'case',
    brand: 'Lian Li',
    model: 'O11 Dynamic EVO',
    description:
      'Dual-chamber showcase case with wide radiator support. The usual choice for builds meant to be looked at.',
    price_cents: 21900,
    supported_form_factors: ['e-atx', 'atx', 'micro-atx', 'mini-itx'],
    max_gpu_length_mm: 423,
    max_cooler_height_mm: 167,
    radiator_support_mm: [240, 280, 360],
    psu_form_factor: 'atx',
    stock_quantity: 5,
    specs: { layout: 'Dual chamber', glass: 'Tempered glass front and side' },
  }),
  component({
    id: 'case-fractal-meshify-2',
    sku: 'CASE-FRA-MESH2',
    category: 'case',
    brand: 'Fractal Design',
    model: 'Meshify 2',
    description:
      'Large airflow-focused case with room for long cards, big radiators and a lot of drives. Suited to workstations.',
    price_cents: 22900,
    supported_form_factors: ['e-atx', 'atx', 'micro-atx', 'mini-itx'],
    max_gpu_length_mm: 460,
    max_cooler_height_mm: 185,
    radiator_support_mm: [240, 280, 360, 420],
    psu_form_factor: 'atx',
    stock_quantity: 4,
    specs: { drive_bays: 'Up to 14 with brackets' },
  }),

  // -------------------------------------------------------------------------
  // Operating systems
  // -------------------------------------------------------------------------
  component({
    id: 'os-none',
    sku: 'OS-NONE',
    category: 'os',
    brand: 'PC Builders Canada',
    model: 'No operating system',
    description:
      'Ships without an OS installed. Choose this if you are supplying your own licence or installing Linux yourself.',
    price_cents: 0,
    cost_cents: 0,
    stock_quantity: 999,
    low_stock_threshold: 0,
    specs: { note: 'System is still tested before shipping using our own bootable media.' },
  }),
  component({
    id: 'os-windows-11-home',
    sku: 'OS-MS-W11HOME',
    category: 'os',
    brand: 'Microsoft',
    model: 'Windows 11 Home',
    description: 'Windows 11 Home licence, installed and updated before the system ships.',
    price_cents: 15900,
    stock_quantity: 999,
    low_stock_threshold: 10,
    specs: { edition: 'Home', delivery: 'Pre-installed and activated' },
  }),
  component({
    id: 'os-windows-11-pro',
    sku: 'OS-MS-W11PRO',
    category: 'os',
    brand: 'Microsoft',
    model: 'Windows 11 Pro',
    description:
      'Windows 11 Pro licence. Adds BitLocker, Remote Desktop host and domain join — the usual choice for work machines.',
    price_cents: 23900,
    stock_quantity: 999,
    low_stock_threshold: 10,
    specs: { edition: 'Pro', delivery: 'Pre-installed and activated' },
  }),

  // -------------------------------------------------------------------------
  // Accessories
  // -------------------------------------------------------------------------
  component({
    id: 'acc-arctic-p12-5pack',
    sku: 'ACC-ARC-P12X5',
    category: 'accessory',
    brand: 'Arctic',
    model: 'P12 PWM PST 120mm fans (5-pack)',
    description: 'Additional case fans for builds that need more intake or exhaust.',
    price_cents: 4900,
    tdp_watts: 8,
    stock_quantity: 16,
    specs: { size_mm: 120, quantity: 5 },
  }),
  component({
    id: 'acc-sleeved-cable-kit',
    sku: 'ACC-PCB-CABLEKIT',
    category: 'accessory',
    brand: 'PC Builders Canada',
    model: 'Sleeved cable extension kit',
    description:
      'Individually sleeved extensions for the visible 24-pin, CPU and GPU cables. Fitted during assembly.',
    price_cents: 5900,
    stock_quantity: 8,
    specs: { note: 'Colour selected after order — we confirm before building.' },
  }),
  component({
    id: 'acc-thermal-paste-upgrade',
    sku: 'ACC-PCB-TIMUP',
    category: 'accessory',
    brand: 'Thermal Grizzly',
    model: 'Kryonaut thermal compound application',
    description:
      'Higher-grade thermal compound applied in place of the cooler default paste.',
    price_cents: 2500,
    stock_quantity: 20,
    specs: { note: 'Applied during assembly' },
  }),
  component({
    id: 'acc-recovery-usb',
    sku: 'ACC-PCB-RECUSB',
    category: 'accessory',
    brand: 'PC Builders Canada',
    model: 'Recovery USB drive',
    description:
      'Bootable USB with the installed OS image and the drivers for your exact configuration, so a reinstall does not need another machine.',
    price_cents: 3500,
    stock_quantity: 25,
    specs: { capacity_gb: 32 },
  }),
];

export const SAMPLE_COMPONENTS_BY_ID = new Map(SAMPLE_COMPONENTS.map((c) => [c.id, c]));
